import type { Theme } from '@/hooks/use-theme';

export interface ThemeDef {
  id: Theme;
  num: number;
  name: string;
  label: string;
  desc: string;
  font: string;
  bg: string;
  border: string;
  wordColor: string;
  wordGlow?: string;
  subColor: string;
  tier: 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J' | 'K';
  /** Carries its own keyframe animation / gradient treatment. */
  animated?: boolean;
  /** Language this theme is themed around, when it is language-specific. */
  language?: string;
  /** Flag tier: the all-in 'ultimate' set, or a single-country 'variant'. */
  flagKind?: 'ultimate' | 'variant';
  /** Bundle id — variants sharing a pack can be sold together. */
  pack?: string;
}

export const THEMES: ThemeDef[] = [
  {
    num: 0,
    id: 'theme-baskin',
    tier: 'A',
    name: 'BASKIN',
    label: '31 Flavors',
    desc: 'Default theme. Rainbow gradient & playful accents. 31 flavors of color.',
    font: "'Outfit', sans-serif",
    bg: '#12101a',
    border: '#e0558a',
    wordColor: '#ff6b9d',
    wordGlow: '0 0 20px #ff6b9d, 0 0 40px #4da6ff',
    subColor: 'rgba(255,107,157,0.5)',
  },
  {
    num: 1,
    id: 'theme-neon',
    tier: 'A',
    name: 'NEON',
    label: 'Neon Arcade',
    desc: 'Cyberpunk arcade cabinet. Electric cyan on black.',
    font: "'Outfit', sans-serif",
    bg: '#0a0a0f',
    border: '#00b4c8',
    wordColor: '#00e5ff',
    wordGlow: '0 0 18px #00e5ff, 0 0 36px #009bb0',
    subColor: 'rgba(0,229,255,0.5)',
  },
  {
    num: 2,
    id: 'theme-void',
    tier: 'A',
    name: 'VOID',
    label: 'Deep Void',
    desc: 'Indigo darkness. Electric blue border glow.',
    font: "'Rajdhani', sans-serif",
    bg: '#07090f',
    border: '#2255cc',
    wordColor: '#5588ff',
    wordGlow: '0 0 18px #5588ff, 0 0 40px #2244aa',
    subColor: 'rgba(85,136,255,0.5)',
  },
  {
    num: 3,
    id: 'theme-matrix',
    tier: 'A',
    name: 'MATRIX',
    label: 'Matrix Code',
    desc: 'Green phosphor monospace. The code is language.',
    font: "'Space Mono', monospace",
    bg: '#020a02',
    border: '#00aa22',
    wordColor: '#00ff41',
    wordGlow: '0 0 15px #00ff41, 0 0 35px #00801a',
    subColor: 'rgba(0,255,65,0.4)',
  },
  {
    num: 4,
    id: 'theme-rose',
    tier: 'A',
    name: 'ROSE',
    label: 'Hot Rose',
    desc: 'Dark with hot-pink neon. Bold and unapologetic.',
    font: "'Outfit', sans-serif",
    bg: '#0d040a',
    border: '#cc2277',
    wordColor: '#ff3399',
    wordGlow: '0 0 18px #ff3399, 0 0 40px #aa1155',
    subColor: 'rgba(255,51,153,0.5)',
  },
  {
    num: 5,
    id: 'theme-lavender',
    tier: 'A',
    name: 'LAVENDER',
    label: 'Soft Violet',
    desc: 'Dark purple haze. Elegant and mysterious.',
    font: "'Josefin Sans', sans-serif",
    bg: '#080612',
    border: '#6633bb',
    wordColor: '#aa77ff',
    wordGlow: '0 0 15px #aa77ff, 0 0 30px #7744cc',
    subColor: 'rgba(170,119,255,0.4)',
  },
  {
    num: 6,
    id: 'theme-arctic',
    tier: 'A',
    name: 'ARCTIC',
    label: 'Icy Blue',
    desc: 'Crisp light sky background. Cool and clean.',
    font: "'Inter', sans-serif",
    bg: '#eaf4fc',
    border: '#5599cc',
    wordColor: '#1a4d7a',
    wordGlow: undefined,
    subColor: '#5599cc',
  },
  {
    num: 22,
    id: 'theme-sakura',
    tier: 'A',
    name: 'SAKURA',
    label: 'Cherry Blossom',
    desc: 'Light pink petals. Soft romantic spring.',
    font: "'Josefin Sans', sans-serif",
    bg: '#fbeef5',
    border: '#d48a9e',
    wordColor: '#7a2d4e',
    wordGlow: undefined,
    subColor: '#c4708a',
  },
  {
    num: 7,
    id: 'theme-ember',
    tier: 'B',
    name: 'EMBER',
    label: 'Ember Glow',
    desc: 'Dark warmth with amber fire. Intense and inviting.',
    font: "'Outfit', sans-serif",
    bg: '#0a0602',
    border: '#cc7700',
    wordColor: '#ffaa22',
    wordGlow: '0 0 20px #ffaa22, 0 0 45px #bb6600',
    subColor: 'rgba(255,170,34,0.5)',
  },
  {
    num: 8,
    id: 'theme-crimson',
    tier: 'B',
    name: 'CRIMSON',
    label: 'Dark Crimson',
    desc: 'Near-black with deep red power. Condensed and bold.',
    font: "'Bebas Neue', sans-serif",
    bg: '#080202',
    border: '#880000',
    wordColor: '#dd2222',
    wordGlow: '0 0 20px #dd2222, 0 0 50px #880000',
    subColor: 'rgba(221,34,34,0.5)',
  },
  {
    num: 9,
    id: 'theme-sand',
    tier: 'B',
    name: 'SAND/GOLD',
    label: 'Sand & Gold',
    desc: 'Warm parchment. Luxury language institute serif.',
    font: "'Playfair Display', serif",
    bg: '#f5efe0',
    border: '#8B6914',
    wordColor: '#6b4f0f',
    wordGlow: undefined,
    subColor: '#a07820',
  },
  {
    num: 10,
    id: 'theme-eink',
    tier: 'B',
    name: 'E-INK',
    label: 'E-Ink Minimal',
    desc: 'Pure white, zero decoration. Premium reader aesthetic.',
    font: "'Inter', sans-serif",
    bg: '#ffffff',
    border: '#e0e0e0',
    wordColor: '#111111',
    wordGlow: undefined,
    subColor: '#666666',
  },
  {
    num: 11,
    id: 'theme-phantom',
    tier: 'B',
    name: 'PHANTOM',
    label: 'Ghost Grey',
    desc: 'Dark charcoal with silver text. Understated elegance.',
    font: "'Josefin Sans', sans-serif",
    bg: '#0c0d10',
    border: '#333a44',
    wordColor: '#cccccc',
    wordGlow: '0 0 12px rgba(255,255,255,0.35)',
    subColor: '#888888',
  },
  {
    num: 12,
    id: 'theme-typewriter',
    tier: 'B',
    name: 'MONO TYPE',
    label: 'Typewriter',
    desc: 'Cream paper. The satisfying clack of keys.',
    font: "'Special Elite', cursive",
    bg: '#f0ead8',
    border: '#bba882',
    wordColor: '#2e1f0e',
    wordGlow: undefined,
    subColor: '#7a6040',
  },
  {
    num: 23,
    id: 'theme-forest',
    tier: 'B',
    name: 'FOREST',
    label: 'Woodland Deep',
    desc: 'Dark forest green. Rich earthy moss tones.',
    font: "'DM Serif Display', serif",
    bg: '#060f06',
    border: '#1a4a1a',
    wordColor: '#66ee66',
    wordGlow: '0 0 15px #44cc44, 0 0 35px #228822',
    subColor: 'rgba(102,238,102,0.45)',
  },
  {
    num: 13,
    id: 'theme-abyss',
    tier: 'C',
    name: 'ABYSS',
    label: 'Abyssal Navy',
    desc: 'Deep navy with Orbitron tech. Space station terminal.',
    font: "'Orbitron', sans-serif",
    bg: '#020510',
    border: '#1a3880',
    wordColor: '#6699ff',
    wordGlow: '0 0 25px #6699ff, 0 0 55px #334499',
    subColor: 'rgba(102,153,255,0.5)',
  },
  {
    num: 14,
    id: 'theme-espresso',
    tier: 'C',
    name: 'ESPRESSO',
    label: 'Dark Coffee',
    desc: 'Warm dark brown. Rich roasted tones.',
    font: "'Playfair Display', serif",
    bg: '#080402',
    border: '#664422',
    wordColor: '#cc8844',
    wordGlow: '0 0 15px #cc8844',
    subColor: 'rgba(204,136,68,0.5)',
  },
  {
    num: 15,
    id: 'theme-cosmos',
    tier: 'C',
    name: 'COSMOS',
    label: 'Constellation',
    desc: 'Starfield dark. Navigate by the stars.',
    font: "'Josefin Sans', sans-serif",
    bg: '#020309',
    border: '#1a2255',
    wordColor: '#88bbdd',
    wordGlow: '0 0 20px #88bbdd, 0 0 50px #3355aa',
    subColor: 'rgba(136,187,221,0.4)',
  },
  {
    num: 16,
    id: 'theme-electric',
    tier: 'C',
    name: 'ELECTRIC',
    label: 'Electric Blue',
    desc: 'Vivid electric blue background. Pure energy.',
    font: "'Bebas Neue', sans-serif",
    bg: '#0055cc',
    border: '#3388ff',
    wordColor: '#ffffff',
    wordGlow: '0 0 20px rgba(255,255,255,0.6)',
    subColor: 'rgba(255,255,255,0.7)',
  },
  {
    num: 17,
    id: 'theme-chalk',
    tier: 'C',
    name: 'CHALK',
    label: 'Chalk White',
    desc: 'Soft off-white. Clean and intentional.',
    font: "'Inter', sans-serif",
    bg: '#f4f5f7',
    border: '#c8cdd6',
    wordColor: '#1a2035',
    wordGlow: undefined,
    subColor: '#6677aa',
  },
  {
    num: 18,
    id: 'theme-onyx',
    tier: 'C',
    name: 'ONYX',
    label: 'Onyx Texture',
    desc: 'Ultra-dark charcoal with subtle grain. Premium dark.',
    font: "'Outfit', sans-serif",
    bg: '#0c0d0f',
    border: '#222428',
    wordColor: '#e0e2e6',
    wordGlow: '0 0 10px rgba(255,255,255,0.15)',
    subColor: 'rgba(224,226,230,0.45)',
  },
  {
    num: 24,
    id: 'theme-midnight',
    tier: 'C',
    name: 'MIDNIGHT',
    label: 'Midnight Gold',
    desc: 'Deep navy with golden stars. Regal and vast.',
    font: "'Unbounded', sans-serif",
    bg: '#040612',
    border: '#223388',
    wordColor: '#ffcc33',
    wordGlow: '0 0 25px #ffcc33, 0 0 50px #cc8800',
    subColor: 'rgba(255,204,51,0.45)',
  },
  {
    num: 25,
    id: 'theme-steel',
    tier: 'C',
    name: 'STEEL',
    label: 'Industrial Steel',
    desc: 'Blue-grey industrial. Sharp utilitarian design.',
    font: "'Barlow Condensed', sans-serif",
    bg: '#0d1014',
    border: '#2a333d',
    wordColor: '#b0c4d8',
    wordGlow: '0 0 12px rgba(176,196,216,0.3)',
    subColor: 'rgba(176,196,216,0.5)',
  },
  {
    num: 19,
    id: 'theme-aurora',
    tier: 'D',
    name: 'AURORA',
    label: 'Aurora Drift',
    desc: 'Animated green aurora. Living gradient glow.',
    font: "'Outfit', sans-serif",
    bg: '#020c04',
    border: '#116622',
    wordColor: '#44ff88',
    wordGlow: '0 0 25px #44ff88, 0 0 60px #22cc55',
    subColor: 'rgba(68,255,136,0.45)',
  },
  {
    num: 20,
    id: 'theme-nebula',
    tier: 'D',
    name: 'NEBULA',
    label: 'Nebula Drift',
    desc: 'Teal-purple animated drift. Deep space wonder.',
    font: "'Orbitron', sans-serif",
    bg: '#04020d',
    border: '#2a1155',
    wordColor: '#22ddcc',
    wordGlow: '0 0 30px #22ddcc, 0 0 70px #7733cc',
    subColor: 'rgba(34,221,204,0.4)',
  },
  {
    num: 21,
    id: 'theme-chrome',
    tier: 'D',
    name: '·TRES·',
    label: 'Chrome',
    desc: 'Metallic silver holographic. Mirror-finish.',
    font: "'Bebas Neue', sans-serif",
    bg: '#0e1014',
    border: '#44494f',
    wordColor: '#d0d4da',
    wordGlow: '0 0 10px rgba(255,255,255,0.4), 0 2px 0 rgba(0,0,0,0.5)',
    subColor: 'rgba(200,205,212,0.5)',
  },
  {
    num: 26,
    id: 'theme-horizon',
    tier: 'D',
    name: 'HORIZON',
    label: 'Sunset Drift',
    desc: 'Animated sunset gradient. Warm crimson to gold.',
    font: "'DM Serif Display', serif",
    bg: '#080305',
    border: '#772233',
    wordColor: '#ff8844',
    wordGlow: '0 0 25px #ff8844, 0 0 60px #dd2244',
    subColor: 'rgba(255,136,68,0.45)',
  },
  {
    num: 27,
    id: 'theme-cyberwave',
    tier: 'D',
    name: 'WAVER',
    label: 'Cyberwave',
    desc: 'Animated cyberpunk wave. Glitch neon energy.',
    font: "'Unbounded', sans-serif",
    bg: '#08020e',
    border: '#552299',
    wordColor: '#cc44ff',
    wordGlow: '0 0 20px #cc44ff, 0 0 50px #ff2277, 0 0 80px #6622cc',
    subColor: 'rgba(204,68,255,0.45)',
  },
  {
    num: 28,
    id: 'theme-ocean',
    tier: 'D',
    name: 'OCEAN',
    label: 'Deep Ocean',
    desc: 'Animated deep ocean wave. Teal and cobalt.',
    font: "'Josefin Sans', sans-serif",
    bg: '#030a0e',
    border: '#115566',
    wordColor: '#33dddd',
    wordGlow: '0 0 25px #33dddd, 0 0 60px #2255cc',
    subColor: 'rgba(51,221,221,0.4)',
  },
  {
    num: 29,
    id: 'theme-embers',
    tier: 'D',
    name: 'EMBERS',
    label: 'Glowing Embers',
    desc: 'Animated ember pulse. Fire and charcoal.',
    font: "'Playfair Display', serif",
    bg: '#070303',
    border: '#662211',
    wordColor: '#ff6633',
    wordGlow: '0 0 20px #ff6633, 0 0 50px #cc2200',
    subColor: 'rgba(255,102,51,0.5)',
  },
  {
    num: 30,
    id: 'theme-flamenco',
    tier: 'E',
    name: 'FLAMENCO',
    label: 'Flamenco (es)',
    desc: 'Spanish spirit — warm gold, red lace, passionate.',
    font: "'Playfair Display', serif",
    bg: '#0a0404',
    border: '#992233',
    wordColor: '#ee4455',
    wordGlow: '0 0 20px #ee4455, 0 0 45px #cc8800',
    subColor: 'rgba(238,68,85,0.5)',
  },
  {
    num: 31,
    id: 'theme-wabi',
    tier: 'E',
    name: 'WABI',
    label: 'Wabi-Sabi (ja)',
    desc: 'Japanese zen — ink wash, washi paper, imperfection.',
    font: "'Noto Sans JP', sans-serif",
    bg: '#efece6',
    border: '#b8b0a2',
    wordColor: '#2c2418',
    wordGlow: undefined,
    subColor: '#8a7e6b',
  },
  {
    num: 32,
    id: 'theme-ultimate',
    tier: 'F',
    name: 'ULTIMATE',
    label: 'Liquid Glass',
    desc: 'Liquid glass · glitch FX · Apple precision · Ultimate tier.',
    font: "'Major Mono Display', monospace",
    bg: '#0a0a0f',
    border: '#00eecc',
    wordColor: '#00ffdd',
    wordGlow: '0 0 25px #00ffdd, 0 0 60px #00eecc, 0 0 100px #005555',
    subColor: 'rgba(0,255,221,0.5)',
  },
  {
    num: 33,
    id: 'theme-acid-rain',
    tier: 'G',
    name: 'ACID RAIN',
    label: 'Acid Rain',
    desc: 'Corroded green rain on soot. Everything is dissolving.',
    font: "'Space Mono', monospace",
    bg: '#080c08',
    border: '#097000',
    wordColor: '#4cff4c',
    wordGlow: '0 0 22px #4cff4c, 0 0 52px #00aa22',
    subColor: '#15ff008c',
  },
  {
    num: 34,
    id: 'theme-vaporwave',
    tier: 'G',
    name: 'VAPORWAVE',
    label: 'Vapor Dream',
    desc: 'Sun-bleached mall aesthetic. Pink grid to the horizon.',
    font: "'Outfit', sans-serif",
    bg: '#170c1d',
    border: '#d6008f',
    wordColor: '#ff71ce',
    wordGlow: '0 0 22px #ff71ce, 0 0 52px #01cdfe',
    subColor: '#ff66cc8c',
  },
  {
    num: 35,
    id: 'theme-blacklight',
    tier: 'G',
    name: 'BLACKLIGHT',
    label: 'Blacklight',
    desc: 'UV wash on a dark room. Everything fluoresces.',
    font: "'Rajdhani', sans-serif",
    bg: '#0c0712',
    border: '#7700cc',
    wordColor: '#b388ff',
    wordGlow: '0 0 22px #b388ff, 0 0 52px #7c4dff',
    subColor: '#bb5cff8c',
  },
  {
    num: 36,
    id: 'theme-magma',
    tier: 'G',
    name: 'MAGMA',
    label: 'Magma Core',
    desc: 'Molten rock under pressure. Cracks of orange light.',
    font: "'Outfit', sans-serif",
    bg: '#120a07',
    border: '#8a2e00',
    wordColor: '#ff5722',
    wordGlow: '0 0 22px #ff5722, 0 0 52px #ff9100',
    subColor: '#ff661a8c',
  },
  {
    num: 37,
    id: 'theme-radioactive',
    tier: 'G',
    name: 'RADIOACTIVE',
    label: 'Radioactive',
    desc: 'Hazard yellow on containment black. Do not linger.',
    font: "'Space Mono', monospace",
    bg: '#0f0f0a',
    border: '#7a7600',
    wordColor: '#e8ff00',
    wordGlow: '0 0 22px #e8ff00, 0 0 52px #aacc00',
    subColor: '#fff70a8c',
  },
  {
    num: 38,
    id: 'theme-bubblegum',
    tier: 'G',
    name: 'BUBBLEGUM',
    label: 'Bubblegum',
    desc: 'Chewed-pink sugar rush. Loud and unrepentant.',
    font: "'Outfit', sans-serif",
    bg: '#22111a',
    border: '#d60059',
    wordColor: '#ff4fa3',
    wordGlow: '0 0 22px #ff4fa3, 0 0 52px #ff9ecb',
    subColor: '#ff66a68c',
  },
  {
    num: 39,
    id: 'theme-oil-slick',
    tier: 'G',
    name: 'OIL SLICK',
    label: 'Oil Slick',
    desc: 'Iridescent film on black water. Shifts as you move.',
    font: "'Rajdhani', sans-serif",
    bg: '#07070d',
    border: '#630da0',
    wordColor: '#8f6dff',
    wordGlow: '0 0 22px #8f6dff, 0 0 52px #22d3b8',
    subColor: '#ac4cf08c',
  },
  {
    num: 40,
    id: 'theme-infrared',
    tier: 'G',
    name: 'INFRARED',
    label: 'Infrared',
    desc: 'Thermal bloom. Heat signatures in the dark.',
    font: "'Space Mono', monospace",
    bg: '#0e0606',
    border: '#8a0000',
    wordColor: '#ff2d2d',
    wordGlow: '0 0 22px #ff2d2d, 0 0 52px #8b0000',
    subColor: '#ff1a1a8c',
  },
  {
    num: 41,
    id: 'theme-plasma',
    tier: 'G',
    name: 'PLASMA',
    label: 'Plasma Arc',
    desc: 'Contained lightning. Magenta discharge on blue.',
    font: "'Rajdhani', sans-serif",
    bg: '#090613',
    border: '#ad00bd',
    wordColor: '#e040fb',
    wordGlow: '0 0 22px #e040fb, 0 0 52px #2979ff',
    subColor: '#f04dff8c',
  },
  {
    num: 42,
    id: 'theme-solar-flare',
    tier: 'G',
    name: 'SOLAR FLARE',
    label: 'Solar Flare',
    desc: 'White-hot corona. Too bright to look at directly.',
    font: "'Outfit', sans-serif",
    bg: '#0f0b05',
    border: '#996600',
    wordColor: '#ffb300',
    wordGlow: '0 0 22px #ffb300, 0 0 52px #ff6d00',
    subColor: '#ffb8298c',
  },
  {
    num: 43,
    id: 'theme-glitch',
    tier: 'G',
    name: 'GLITCH',
    label: 'Signal Glitch',
    desc: 'Torn signal. Channels bleeding into each other.',
    font: "'Space Mono', monospace",
    bg: '#080808',
    border: '#a30029',
    wordColor: '#ff0055',
    wordGlow: '0 0 22px #ff0055, 0 0 52px #00fff0',
    subColor: '#ff33668c',
  },
  {
    num: 44,
    id: 'theme-toxic-slime',
    tier: 'G',
    name: 'TOXIC SLIME',
    label: 'Toxic Slime',
    desc: 'Dripping lime sludge. Faintly luminous.',
    font: "'Outfit', sans-serif",
    bg: '#0b1109',
    border: '#2f7000',
    wordColor: '#aaff00',
    wordGlow: '0 0 22px #aaff00, 0 0 52px #00ff88',
    subColor: '#6aff008c',
  },
  {
    num: 45,
    id: 'theme-deep-sea',
    tier: 'G',
    name: 'DEEP SEA',
    label: 'Abyssal Bloom',
    desc: 'Bioluminescence at crushing depth. Nothing else glows.',
    font: "'Rajdhani', sans-serif",
    bg: '#040c10',
    border: '#007070',
    wordColor: '#00e5c0',
    wordGlow: '0 0 22px #00e5c0, 0 0 52px #0066ff',
    subColor: '#00ffff8c',
  },
  {
    num: 46,
    id: 'theme-supernova',
    tier: 'G',
    name: 'SUPERNOVA',
    label: 'Supernova',
    desc: 'A star coming apart. Gold shockfront on void.',
    font: "'Outfit', sans-serif",
    bg: '#05060b',
    border: '#ad8b00',
    wordColor: '#ffd54f',
    wordGlow: '0 0 22px #ffd54f, 0 0 52px #b388ff',
    subColor: '#ffd83d8c',
  },
  {
    num: 47,
    id: 'theme-venom',
    tier: 'G',
    name: 'VENOM',
    label: 'Venom',
    desc: 'Purple toxin, green antivenom. Pick one.',
    font: "'Rajdhani', sans-serif",
    bg: '#0b050f',
    border: '#8200ad',
    wordColor: '#a855f7',
    wordGlow: '0 0 22px #a855f7, 0 0 52px #39ff14',
    subColor: '#cf3dff8c',
  },
  {
    num: 48,
    id: 'theme-hologram',
    tier: 'G',
    name: 'HOLOGRAM',
    label: 'Hologram',
    desc: 'Projected light with no substance. Flickers at the edges.',
    font: "'Space Mono', monospace",
    bg: '#061013',
    border: '#0096a3',
    wordColor: '#5ce1e6',
    wordGlow: '0 0 22px #5ce1e6, 0 0 52px #ff6ec7',
    subColor: '#33eeff8c',
  },
  {
    num: 49,
    id: 'theme-inferno',
    tier: 'G',
    name: 'INFERNO',
    label: 'Inferno',
    desc: 'Full burn. Orange tongues on charcoal.',
    font: "'Outfit', sans-serif",
    bg: '#0a0705',
    border: '#7a3300',
    wordColor: '#ff6b00',
    wordGlow: '0 0 22px #ff6b00, 0 0 52px #ff1744',
    subColor: '#ff700a8c',
  },
  {
    num: 50,
    id: 'theme-cotton-candy',
    tier: 'G',
    name: 'COTTON CANDY',
    label: 'Cotton Candy',
    desc: 'Spun pastel floss. Sweet enough to hurt.',
    font: "'Outfit', sans-serif",
    bg: '#1e101e',
    border: '#f20da6',
    wordColor: '#ffb3de',
    wordGlow: '0 0 22px #ffb3de, 0 0 52px #b3e5ff',
    subColor: '#f994d88c',
  },
  {
    num: 51,
    id: 'theme-circuit',
    tier: 'G',
    name: 'CIRCUIT',
    label: 'Circuit Board',
    desc: 'Etched traces and gold pads. Solder-mask green.',
    font: "'Space Mono', monospace",
    bg: '#07120d',
    border: '#045225',
    wordColor: '#2fd96f',
    wordGlow: '0 0 22px #2fd96f, 0 0 52px #ffc107',
    subColor: '#0bda628c',
  },
  {
    num: 52,
    id: 'theme-eclipse',
    tier: 'G',
    name: 'ECLIPSE',
    label: 'Total Eclipse',
    desc: 'Blacked-out disc, corona burning around the rim.',
    font: "'Rajdhani', sans-serif",
    bg: '#050505',
    border: '#9f6b04',
    wordColor: '#ffca28',
    wordGlow: '0 0 22px #ffca28, 0 0 52px #ffffff',
    subColor: '#fab9388c',
  },
  {
    num: 53,
    id: 'theme-kanso',
    tier: 'H',
    name: 'KANSO',
    label: 'Kansō 簡素',
    desc: 'Sumi ink on washi. Restraint as decoration.',
    font: "'Playfair Display', serif",
    bg: '#141210',
    border: '#721818',
    wordColor: '#e8e2d4',
    wordGlow: '0 0 20px #c8482f, 0 0 48px #2b2b2b',
    subColor: '#d742428c',
    language: 'ja',
  },
  {
    num: 54,
    id: 'theme-shinjuku',
    tier: 'H',
    name: 'SHINJUKU',
    label: 'Shinjuku Night',
    desc: 'Rain-slick neon over Kabukichō. Signage in every direction.',
    font: "'Rajdhani', sans-serif",
    bg: '#130816',
    border: '#ad0057',
    wordColor: '#ff2e88',
    wordGlow: '0 0 20px #ff2e88, 0 0 48px #00d9ff',
    subColor: '#ff3d9e8c',
    language: 'ja',
  },
  {
    num: 55,
    id: 'theme-flamenco-noche',
    tier: 'H',
    name: 'FLAMENCO NOCHE',
    label: 'Flamenco Nights',
    desc: 'Blood red on black lace. Heel strikes and guitar.',
    font: "'Playfair Display', serif",
    bg: '#15090b',
    border: '#6b0613',
    wordColor: '#d62828',
    wordGlow: '0 0 20px #d62828, 0 0 48px #f77f00',
    subColor: '#f20d2b8c',
    language: 'es',
  },
  {
    num: 56,
    id: 'theme-azulejo',
    tier: 'H',
    name: 'AZULEJO',
    label: 'Azulejo',
    desc: 'Painted tin-glaze tile. Cobalt on lime white.',
    font: "'Outfit', sans-serif",
    bg: '#0b1a28',
    border: '#0a3b7f',
    wordColor: '#2a6fdb',
    wordGlow: '0 0 20px #2a6fdb, 0 0 48px #ffd166',
    subColor: '#2b7cee8c',
    language: 'pt',
  },
  {
    num: 57,
    id: 'theme-bistro',
    tier: 'H',
    name: 'BISTRO',
    label: 'Bistro Paris',
    desc: 'Zinc bar, cream awning, a little too much red wine.',
    font: "'Playfair Display', serif",
    bg: '#11151d',
    border: '#5f1117',
    wordColor: '#e5c185',
    wordGlow: '0 0 20px #c1121f, 0 0 48px #3d5a80',
    subColor: '#d926358c',
    language: 'fr',
  },
  {
    num: 58,
    id: 'theme-bauhaus',
    tier: 'H',
    name: 'BAUHAUS',
    label: 'Bauhaus',
    desc: 'Primary blocks, hard grid, zero ornament.',
    font: "'Rajdhani', sans-serif",
    bg: '#141414',
    border: '#710909',
    wordColor: '#e63946',
    wordGlow: '0 0 20px #e63946, 0 0 48px #f1c40f',
    subColor: '#ed1d1d8c',
    language: 'de',
  },
  {
    num: 59,
    id: 'theme-rinascimento',
    tier: 'H',
    name: 'RINASCIMENTO',
    label: 'Rinascimento',
    desc: 'Fresco ochre and duomo green. Quietly enormous.',
    font: "'Playfair Display', serif",
    bg: '#1b130e',
    border: '#123624',
    wordColor: '#c8963e',
    wordGlow: '0 0 20px #c8963e, 0 0 48px #2a9d5c',
    subColor: '#36a16b8c',
    language: 'it',
  },
  {
    num: 60,
    id: 'theme-samovar',
    tier: 'H',
    name: 'SAMOVAR',
    label: 'Samovar',
    desc: 'Lacquered black, gold leaf, constructivist red.',
    font: "'Space Mono', monospace",
    bg: '#120c0c',
    border: '#5c0a0a',
    wordColor: '#d4a017',
    wordGlow: '0 0 20px #c1121f, 0 0 48px #d4a017',
    subColor: '#dc18188c',
    language: 'ru',
  },
  {
    num: 61,
    id: 'theme-hanbok',
    tier: 'H',
    name: 'HANBOK',
    label: 'Hanbok',
    desc: 'Silk panels: persimmon, indigo, jade.',
    font: "'Outfit', sans-serif",
    bg: '#0e101b',
    border: '#972f0c',
    wordColor: '#ff7043',
    wordGlow: '0 0 20px #ff7043, 0 0 48px #26a69a',
    subColor: '#f06e428c',
    language: 'ko',
  },
  {
    num: 62,
    id: 'theme-qinghua',
    tier: 'H',
    name: 'QINGHUA',
    label: 'Qīnghuā 青花',
    desc: 'Blue-and-white porcelain under a red seal.',
    font: "'Playfair Display', serif",
    bg: '#0d1521',
    border: '#0c2d6e',
    wordColor: '#3f7cd6',
    wordGlow: '0 0 20px #3f7cd6, 0 0 48px #c1272d',
    subColor: '#2364e78c',
    language: 'zh',
  },
  {
    num: 63,
    id: 'theme-zellige',
    tier: 'H',
    name: 'ZELLIGE',
    label: 'Zellige',
    desc: 'Interlocking tilework, mint tea, brass lamplight.',
    font: "'Outfit', sans-serif",
    bg: '#0a171a',
    border: '#093e3a',
    wordColor: '#1eb5a6',
    wordGlow: '0 0 20px #1eb5a6, 0 0 48px #e0a800',
    subColor: '#1bbbae8c',
    language: 'ar',
  },
  {
    num: 64,
    id: 'theme-holi',
    tier: 'H',
    name: 'HOLI',
    label: 'Holi',
    desc: 'Powder thrown mid-air. Every colour at once.',
    font: "'Outfit', sans-serif",
    bg: '#1c0d1c',
    border: '#a90457',
    wordColor: '#ff4da6',
    wordGlow: '0 0 20px #ff4da6, 0 0 48px #ffd000',
    subColor: '#fa429e8c',
    language: 'hi',
  },
  {
    num: 65,
    id: 'theme-delftware',
    tier: 'H',
    name: 'DELFTWARE',
    label: 'Delftware',
    desc: 'Canal-house blue on chalk white.',
    font: "'Outfit', sans-serif",
    bg: '#0f1824',
    border: '#0e2d62',
    wordColor: '#3b6fc4',
    wordGlow: '0 0 20px #3b6fc4, 0 0 48px #ff8c1a',
    subColor: '#2066df8c',
    language: 'nl',
  },
  {
    num: 66,
    id: 'theme-lagom',
    tier: 'H',
    name: 'LAGOM',
    label: 'Lagom',
    desc: 'Pale birch, deep blue, exactly enough.',
    font: "'Outfit', sans-serif",
    bg: '#121a21',
    border: '#0c3d6e',
    wordColor: '#4d8ee0',
    wordGlow: '0 0 20px #4d8ee0, 0 0 48px #ffd447',
    subColor: '#2385e78c',
    language: 'sv',
  },
  {
    num: 67,
    id: 'theme-iznik',
    tier: 'H',
    name: 'IZNIK',
    label: 'İznik',
    desc: 'Turquoise and coral on a tulip ground.',
    font: "'Outfit', sans-serif",
    bg: '#0a1b1f',
    border: '#094e4e',
    wordColor: '#1fc4b5',
    wordGlow: '0 0 20px #1fc4b5, 0 0 48px #ff5c4d',
    subColor: '#17cfcf8c',
    language: 'tr',
  },
  {
    num: 68,
    id: 'theme-wat',
    tier: 'H',
    name: 'WAT',
    label: 'Wat Gold',
    desc: 'Temple gilt against monsoon dusk.',
    font: "'Outfit', sans-serif",
    bg: '#130c18',
    border: '#866603',
    wordColor: '#ffc233',
    wordGlow: '0 0 20px #ffc233, 0 0 48px #b06ad6',
    subColor: '#f9c31f8c',
    language: 'th',
  },
  {
    num: 69,
    id: 'theme-sen',
    tier: 'H',
    name: 'SEN',
    label: 'Sen Lotus',
    desc: 'Lacquer red, lotus pink, river green.',
    font: "'Outfit', sans-serif",
    bg: '#180c0d',
    border: '#710912',
    wordColor: '#e63946',
    wordGlow: '0 0 20px #e63946, 0 0 48px #57cc99',
    subColor: '#ed1d2e8c',
    language: 'vi',
  },
  {
    num: 70,
    id: 'theme-kosciuszko',
    tier: 'H',
    name: 'KOŚCIUSZKO',
    label: 'Kościuszko',
    desc: 'Amber, iron white, and a hard winter.',
    font: "'Space Mono', monospace",
    bg: '#121212',
    border: '#620e0e',
    wordColor: '#dc2626',
    wordGlow: '0 0 20px #dc2626, 0 0 48px #f5c518',
    subColor: '#df20208c',
    language: 'pl',
  },
  {
    num: 71,
    id: 'theme-flag-ultimate',
    tier: 'I',
    name: 'WORLD FLAGS',
    label: 'World Flags · Ultimate',
    desc: 'Every flag in the roster, cycling behind the word. The complete set.',
    font: "'Outfit', sans-serif",
    bg: '#080b11',
    border: '#084c91',
    wordColor: '#ffffff',
    wordGlow: '0 0 20px #4d9fff, 0 0 48px #ff4d6d',
    subColor: '#3494f48c',
    flagKind: 'ultimate',
    pack: 'flag-pack',
  },
  {
    num: 72,
    id: 'theme-flag-es',
    tier: 'I',
    name: 'ROJIGUALDA',
    label: 'Spain · Flag',
    desc: 'Gualda gold between two bands of red.',
    font: "'Outfit', sans-serif",
    bg: '#1a0a0a',
    border: '#680808',
    wordColor: '#ffc400',
    wordGlow: '0 0 20px #c60b1e, 0 0 48px #ffc400',
    subColor: '#ec13138c',
    flagKind: 'variant',
    language: 'es',
    pack: 'flag-pack',
  },
  {
    num: 73,
    id: 'theme-flag-ja',
    tier: 'I',
    name: 'HINOMARU',
    label: 'Japan · Flag',
    desc: 'One red disc, centred, on white.',
    font: "'Outfit', sans-serif",
    bg: '#121212',
    border: '#710912',
    wordColor: '#ffffff',
    wordGlow: '0 0 20px #bc002d, 0 0 48px #ffffff',
    subColor: '#ed1d2e8c',
    flagKind: 'variant',
    language: 'ja',
    pack: 'flag-pack',
  },
  {
    num: 74,
    id: 'theme-flag-fr',
    tier: 'I',
    name: 'TRICOLORE',
    label: 'France · Flag',
    desc: 'Bleu, blanc, rouge in equal measure.',
    font: "'Outfit', sans-serif",
    bg: '#0b0f19',
    border: '#0c256e',
    wordColor: '#ffffff',
    wordGlow: '0 0 20px #0055a4, 0 0 48px #ef4135',
    subColor: '#2354e78c',
    flagKind: 'variant',
    language: 'fr',
    pack: 'flag-pack',
  },
  {
    num: 75,
    id: 'theme-flag-de',
    tier: 'I',
    name: 'SCHWARZ ROT GOLD',
    label: 'Germany · Flag',
    desc: 'Black, red, gold stacked heavy.',
    font: "'Rajdhani', sans-serif",
    bg: '#0d0d0d',
    border: '#5c0a0a',
    wordColor: '#ffce00',
    wordGlow: '0 0 20px #dd0000, 0 0 48px #ffce00',
    subColor: '#dc18188c',
    flagKind: 'variant',
    language: 'de',
    pack: 'flag-pack',
  },
  {
    num: 76,
    id: 'theme-flag-it',
    tier: 'I',
    name: 'IL TRICOLORE',
    label: 'Italy · Flag',
    desc: 'Green, white, red off the flagpole.',
    font: "'Outfit', sans-serif",
    bg: '#0a150e',
    border: '#08361b',
    wordColor: '#ffffff',
    wordGlow: '0 0 20px #009246, 0 0 48px #ce2b37',
    subColor: '#19b3598c',
    flagKind: 'variant',
    language: 'it',
    pack: 'flag-pack',
  },
  {
    num: 77,
    id: 'theme-flag-pt',
    tier: 'I',
    name: 'VERDE RUBRO',
    label: 'Portugal · Flag',
    desc: 'Green and red split by the armillary sphere.',
    font: "'Outfit', sans-serif",
    bg: '#09150f',
    border: '#052e1a',
    wordColor: '#ffe000',
    wordGlow: '0 0 20px #006600, 0 0 48px #ff0000',
    subColor: '#12a1598c',
    flagKind: 'variant',
    language: 'pt',
    pack: 'flag-pack',
  },
  {
    num: 78,
    id: 'theme-flag-br',
    tier: 'I',
    name: 'VERDE AMARELA',
    label: 'Brazil · Flag',
    desc: 'Green field, gold rhombus, blue globe.',
    font: "'Outfit', sans-serif",
    bg: '#08160e',
    border: '#042f16',
    wordColor: '#ffdf00',
    wordGlow: '0 0 20px #009c3b, 0 0 48px #002776',
    subColor: '#0fb3538c',
    flagKind: 'variant',
    language: 'pt',
    pack: 'flag-pack',
  },
  {
    num: 79,
    id: 'theme-flag-zh',
    tier: 'I',
    name: 'WUXING',
    label: 'China · Flag',
    desc: 'Five gold stars on scarlet.',
    font: "'Outfit', sans-serif",
    bg: '#1b090a',
    border: '#5e080f',
    wordColor: '#ffde00',
    wordGlow: '0 0 20px #de2910, 0 0 48px #ffde00',
    subColor: '#e212248c',
    flagKind: 'variant',
    language: 'zh',
    pack: 'flag-pack',
  },
  {
    num: 80,
    id: 'theme-flag-ko',
    tier: 'I',
    name: 'TAEGUKGI',
    label: 'Korea · Flag',
    desc: 'Taegeuk red and blue, four trigrams.',
    font: "'Outfit', sans-serif",
    bg: '#121212',
    border: '#0b2965',
    wordColor: '#ffffff',
    wordGlow: '0 0 20px #0047a0, 0 0 48px #cd2e3a',
    subColor: '#195ee68c',
    flagKind: 'variant',
    language: 'ko',
    pack: 'flag-pack',
  },
  {
    num: 81,
    id: 'theme-flag-ru',
    tier: 'I',
    name: 'TRIKOLOR',
    label: 'Russia · Flag',
    desc: 'White, blue, red in three bands.',
    font: "'Space Mono', monospace",
    bg: '#0a0e15',
    border: '#0a255c',
    wordColor: '#ffffff',
    wordGlow: '0 0 20px #0039a6, 0 0 48px #d52b1e',
    subColor: '#185adc8c',
    flagKind: 'variant',
    language: 'ru',
    pack: 'flag-pack',
  },
  {
    num: 82,
    id: 'theme-flag-in',
    tier: 'I',
    name: 'TIRANGA',
    label: 'India · Flag',
    desc: 'Saffron, white, green around the chakra.',
    font: "'Outfit', sans-serif",
    bg: '#19120b',
    border: '#834107',
    wordColor: '#ff9933',
    wordGlow: '0 0 20px #ff9933, 0 0 48px #138808',
    subColor: '#f485258c',
    flagKind: 'variant',
    language: 'hi',
    pack: 'flag-pack',
  },
  {
    num: 83,
    id: 'theme-flag-sa',
    tier: 'I',
    name: 'AL-ALAM',
    label: 'Arabic · Flag',
    desc: 'Green field, white script and sword.',
    font: "'Outfit', sans-serif",
    bg: '#08160f',
    border: '#052e1a',
    wordColor: '#ffffff',
    wordGlow: '0 0 20px #006c35, 0 0 48px #ffffff',
    subColor: '#1093528c',
    flagKind: 'variant',
    language: 'ar',
    pack: 'flag-pack',
  },
  {
    num: 84,
    id: 'theme-flag-nl',
    tier: 'I',
    name: 'NEDERLANDSE',
    label: 'Netherlands · Flag',
    desc: 'Red, white, blue with an orange pennant.',
    font: "'Outfit', sans-serif",
    bg: '#0c1018',
    border: '#09204e',
    wordColor: '#ffffff',
    wordGlow: '0 0 20px #ae1c28, 0 0 48px #ff7f00',
    subColor: '#1754cf8c',
    flagKind: 'variant',
    language: 'nl',
    pack: 'flag-pack',
  },
  {
    num: 85,
    id: 'theme-flag-se',
    tier: 'I',
    name: 'SVERIGE',
    label: 'Sweden · Flag',
    desc: 'Gold cross on deep blue.',
    font: "'Outfit', sans-serif",
    bg: '#09101b',
    border: '#051f42',
    wordColor: '#fecc00',
    wordGlow: '0 0 20px #fecc00, 0 0 48px #006aa7',
    subColor: '#105cc68c',
    flagKind: 'variant',
    language: 'sv',
    pack: 'flag-pack',
  },
  {
    num: 86,
    id: 'theme-flag-tr',
    tier: 'I',
    name: 'AY YILDIZ',
    label: 'Turkey · Flag',
    desc: 'Crescent and star, white on red.',
    font: "'Outfit', sans-serif",
    bg: '#1b090a',
    border: '#5e080f',
    wordColor: '#ffffff',
    wordGlow: '0 0 20px #e30a17, 0 0 48px #ffffff',
    subColor: '#e212248c',
    flagKind: 'variant',
    language: 'tr',
    pack: 'flag-pack',
  },
  {
    num: 87,
    id: 'theme-flag-th',
    tier: 'I',
    name: 'TRAIRONG',
    label: 'Thailand · Flag',
    desc: 'Red, white, and a broad navy band.',
    font: "'Outfit', sans-serif",
    bg: '#080c16',
    border: '#050f2e',
    wordColor: '#ffffff',
    wordGlow: '0 0 20px #2d2a4a, 0 0 48px #a51931',
    subColor: '#1236a18c',
    flagKind: 'variant',
    language: 'th',
    pack: 'flag-pack',
  },
  {
    num: 88,
    id: 'theme-flag-vn',
    tier: 'I',
    name: 'CO DO',
    label: 'Vietnam · Flag',
    desc: 'One gold star on red.',
    font: "'Outfit', sans-serif",
    bg: '#180708',
    border: '#50070d',
    wordColor: '#ffff00',
    wordGlow: '0 0 20px #da251d, 0 0 48px #ffff00',
    subColor: '#d411218c',
    flagKind: 'variant',
    language: 'vi',
    pack: 'flag-pack',
  },
  {
    num: 89,
    id: 'theme-flag-pl',
    tier: 'I',
    name: 'BIALO-CZERWONA',
    label: 'Poland · Flag',
    desc: 'White over red, nothing else needed.',
    font: "'Outfit', sans-serif",
    bg: '#121212',
    border: '#5c0a11',
    wordColor: '#ffffff',
    wordGlow: '0 0 20px #dc143c, 0 0 48px #ffffff',
    subColor: '#dc18298c',
    flagKind: 'variant',
    language: 'pl',
    pack: 'flag-pack',
  },
  {
    num: 90,
    id: 'theme-aurora-borealis',
    tier: 'J',
    name: 'AURORA BOREALIS',
    label: 'Aurora Borealis',
    desc: 'A living sky. Green and violet curtains drift behind every word.',
    font: "'Outfit', sans-serif",
    bg: '#050810',
    border: '#07835a',
    wordColor: '#7CFFCB',
    wordGlow: '0 0 20px #7CFFCB, 0 0 48px #A97CFF',
    subColor: '#25f4af8c',
    animated: true,
  },
  {
    num: 91,
    id: 'theme-liquid-gold',
    tier: 'J',
    name: 'LIQUID GOLD',
    label: 'Liquid Gold',
    desc: 'Poured metal. The word has real specular travel across it.',
    font: "'Playfair Display', serif",
    bg: '#0e0b07',
    border: '#866103',
    wordColor: '#F7D774',
    wordGlow: '0 0 20px #F7D774, 0 0 48px #B8860B',
    subColor: '#f9bb1f8c',
    animated: true,
  },
  {
    num: 92,
    id: 'theme-obsidian-prism',
    tier: 'J',
    name: 'OBSIDIAN PRISM',
    label: 'Obsidian Prism',
    desc: 'Black glass splitting light. Edges catch spectrum as you move.',
    font: "'Rajdhani', sans-serif",
    bg: '#070609',
    border: '#7109a5',
    wordColor: '#FFFFFF',
    wordGlow: '0 0 20px #B06CFF, 0 0 48px #4DE0FF',
    subColor: '#bb47f58c',
    animated: true,
  },
  {
    num: 93,
    id: 'theme-paper-lantern',
    tier: 'J',
    name: 'PAPER LANTERN',
    label: 'Paper Lantern',
    desc: 'Warm light through rice paper. Soft, close, unhurried.',
    font: "'Playfair Display', serif",
    bg: '#140f0b',
    border: '#8e370b',
    wordColor: '#FFD9A0',
    wordGlow: '0 0 20px #FF9E4F, 0 0 48px #B4531E',
    subColor: '#ef76398c',
    animated: true,
  },
  {
    num: 94,
    id: 'theme-quantum-foam',
    tier: 'J',
    name: 'QUANTUM FOAM',
    label: 'Quantum Foam',
    desc: 'Vacuum fluctuation. Particles resolve into letters, briefly.',
    font: "'Space Mono', monospace",
    bg: '#04050b',
    border: '#00738a',
    wordColor: '#66F0FF',
    wordGlow: '0 0 20px #66F0FF, 0 0 48px #FF52C8',
    subColor: '#1ad9ff8c',
    animated: true,
  },
  // ── J-tier additions (nums 95–99) ─────────────────────────
  {
    num: 95,
    id: 'theme-void-circuit',
    tier: 'J',
    name: 'VOID CIRCUIT',
    label: 'Void Circuit',
    desc: 'Circuit traces run through empty space. Every word is a signal.',
    font: "'Space Mono', monospace",
    bg: '#020407',
    border: '#00ff9f',
    wordColor: '#00FF9F',
    wordGlow: '0 0 18px #00FF9F, 0 0 40px #00e88a',
    subColor: 'rgba(0,255,159,0.5)',
    animated: true,
  },
  {
    num: 96,
    id: 'theme-sakura-storm',
    tier: 'J',
    name: 'SAKURA STORM',
    label: 'Sakura Storm',
    desc: "Night blossoms. Petals hold still until they don't.",
    font: "'Noto Serif', serif",
    bg: '#0d0710',
    border: '#ff7eb3',
    wordColor: '#FFB8D6',
    wordGlow: '0 0 22px #FF7EB3, 0 0 50px #cc3d7a',
    subColor: 'rgba(255,126,179,0.5)',
    animated: true,
  },
  {
    num: 97,
    id: 'theme-lava-forge',
    tier: 'J',
    name: 'LAVA FORGE',
    label: 'Lava Forge',
    desc: 'Forged in the deep. The word is still cooling.',
    font: "'Barlow Condensed', sans-serif",
    bg: '#0c0402',
    border: '#ff4500',
    wordColor: '#FF6B35',
    wordGlow: '0 0 24px #FF4500, 0 0 55px #8B1A00',
    subColor: 'rgba(255,107,53,0.5)',
    animated: true,
  },
  {
    num: 98,
    id: 'theme-bioluminescence',
    tier: 'J',
    name: 'BIOLUMINESCENCE',
    label: 'Bioluminescence',
    desc: '2,000 meters down. Only the light you make yourself.',
    font: "'Josefin Sans', sans-serif",
    bg: '#000d14',
    border: '#00e5ff',
    wordColor: '#7FFFEA',
    wordGlow: '0 0 24px #00e5ff, 0 0 60px #005f73',
    subColor: 'rgba(127,255,234,0.5)',
    animated: true,
  },
  {
    num: 99,
    id: 'theme-thunderhead',
    tier: 'J',
    name: 'THUNDERHEAD',
    label: 'Thunderhead',
    desc: 'The sky before it breaks. Potential energy in everything.',
    font: "'Bebas Neue', sans-serif",
    bg: '#070809',
    border: '#a8c0ff',
    wordColor: '#E8F0FF',
    wordGlow: '0 0 18px #a8c0ff, 0 0 42px #4a6fa5',
    subColor: 'rgba(168,192,255,0.5)',
    animated: true,
  },
  // ── K-tier — MYTHIC (nums 100–107) ────────────────────────
  {
    num: 100,
    id: 'theme-starfall',
    tier: 'K',
    name: 'STARFALL',
    label: 'Starfall',
    desc: 'You catch one in your hand. It spells a word.',
    font: "'Cormorant Garamond', serif",
    bg: '#03030a',
    border: '#ffe4a0',
    wordColor: '#FFF4DC',
    wordGlow: '0 0 28px #FFE4A0, 0 0 70px #cc8800',
    subColor: 'rgba(255,228,160,0.5)',
    animated: true,
  },
  {
    num: 101,
    id: 'theme-phantom-signal',
    tier: 'K',
    name: 'PHANTOM SIGNAL',
    label: 'Phantom Signal',
    desc: 'Channel 0. Static resolves into something worth repeating.',
    font: "'VT323', monospace",
    bg: '#010101',
    border: '#39ff14',
    wordColor: '#39FF14',
    wordGlow: '0 0 16px #39FF14, 0 0 36px #22a80c',
    subColor: 'rgba(57,255,20,0.5)',
    animated: true,
  },
  {
    num: 102,
    id: 'theme-dragon-scales',
    tier: 'K',
    name: 'DRAGON SCALES',
    label: 'Dragon Scales',
    desc: 'Each surface catches a different light. Shift your angle.',
    font: "'Cinzel', serif",
    bg: '#050904',
    border: '#2d6a1a',
    wordColor: '#B8FF6A',
    wordGlow: '0 0 24px #88ee44, 0 0 60px #3a8800',
    subColor: 'rgba(184,255,106,0.5)',
    animated: true,
  },
  {
    num: 103,
    id: 'theme-chronos',
    tier: 'K',
    name: 'CHRONOS',
    label: 'Chronos',
    desc: 'Every word has already been spoken. This is just the record.',
    font: "'Cormorant Garamond', serif",
    bg: '#0a0800',
    border: '#c9933a',
    wordColor: '#F5D78E',
    wordGlow: '0 0 20px #c9933a, 0 0 48px #7a5100',
    subColor: 'rgba(201,147,58,0.5)',
    animated: true,
  },
  {
    num: 104,
    id: 'theme-crystalline',
    tier: 'K',
    name: 'CRYSTALLINE',
    label: 'Crystalline',
    desc: "The word forms like frost. Don't breathe on it.",
    font: "'Raleway', sans-serif",
    bg: '#030810',
    border: '#88ccff',
    wordColor: '#C8E8FF',
    wordGlow: '0 0 22px #88CCFF, 0 0 50px #1a5fa8',
    subColor: 'rgba(136,204,255,0.5)',
    animated: true,
  },
  {
    num: 105,
    id: 'theme-prism-break',
    tier: 'K',
    name: 'PRISM BREAK',
    label: 'Prism Break',
    desc: 'White light entered. Something else came out.',
    font: "'Montserrat', sans-serif",
    bg: '#040208',
    border: '#ff55ff',
    wordColor: '#FFFFFF',
    wordGlow: '0 0 0 2px #ff55ff, 0 0 30px #ff00ff, 0 0 60px #0088ff',
    subColor: 'rgba(255,85,255,0.5)',
    animated: true,
  },
  {
    num: 106,
    id: 'theme-shadowrealm',
    tier: 'K',
    name: 'SHADOWREALM',
    label: 'Shadowrealm',
    desc: 'Names have power. Speak this one carefully.',
    font: "'Cinzel Decorative', serif",
    bg: '#010102',
    border: '#4a0a6b',
    wordColor: '#C97EFF',
    wordGlow: '0 0 28px #8833cc, 0 0 65px #4a0a6b, 0 0 100px #200040',
    subColor: 'rgba(138,51,204,0.5)',
    animated: true,
  },
  {
    num: 107,
    id: 'theme-neon-deity',
    tier: 'K',
    name: 'NEON DEITY',
    label: 'Neon Deity',
    desc: "It doesn't need your attention. It has everyone else's.",
    font: "'Rajdhani', sans-serif",
    bg: '#02020f',
    border: '#ff0080',
    wordColor: '#FF0080',
    wordGlow: '0 0 10px #FF0080, 0 0 30px #FF0080, 0 0 60px #ff0080, 0 0 100px #8800aa',
    subColor: 'rgba(255,0,128,0.5)',
    animated: true,
  },
];
