import type { Theme } from '@/hooks/use-theme';

export interface ThemeDef {
  id: Theme;
  num: number;
  name: string;
  label: string;
  desc: string;
  font: string;
  bg: string;
  border: string;
  wordColor: string;
  wordGlow?: string;
  subColor: string;
  tier: 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G';
}

export const THEMES: ThemeDef[] = [
  {
    num: 0,
    id: 'theme-baskin',
    tier: 'A',
    name: 'BASKIN',
    label: '31 Flavors',
    desc: 'Default theme. Rainbow gradient & playful accents. 31 flavors of color.',
    font: "'Outfit', sans-serif",
    bg: '#12101a',
    border: '#e0558a',
    wordColor: '#ff6b9d',
    wordGlow: '0 0 20px #ff6b9d, 0 0 40px #4da6ff',
    subColor: 'rgba(255,107,157,0.5)',
  },
  {
    num: 1,
    id: 'theme-neon',
    tier: 'A',
    name: 'NEON',
    label: 'Neon Arcade',
    desc: 'Cyberpunk arcade cabinet. Electric cyan on black.',
    font: "'Outfit', sans-serif",
    bg: '#0a0a0f',
    border: '#00b4c8',
    wordColor: '#00e5ff',
    wordGlow: '0 0 18px #00e5ff, 0 0 36px #009bb0',
    subColor: 'rgba(0,229,255,0.5)',
  },
  {
    num: 2,
    id: 'theme-void',
    tier: 'A',
    name: 'VOID',
    label: 'Deep Void',
    desc: 'Indigo darkness. Electric blue border glow.',
    font: "'Rajdhani', sans-serif",
    bg: '#07090f',
    border: '#2255cc',
    wordColor: '#5588ff',
    wordGlow: '0 0 18px #5588ff, 0 0 40px #2244aa',
    subColor: 'rgba(85,136,255,0.5)',
  },
  {
    num: 3,
    id: 'theme-matrix',
    tier: 'A',
    name: 'MATRIX',
    label: 'Matrix Code',
    desc: 'Green phosphor monospace. The code is language.',
    font: "'Space Mono', monospace",
    bg: '#020a02',
    border: '#00aa22',
    wordColor: '#00ff41',
    wordGlow: '0 0 15px #00ff41, 0 0 35px #00801a',
    subColor: 'rgba(0,255,65,0.4)',
  },
  {
    num: 4,
    id: 'theme-rose',
    tier: 'A',
    name: 'ROSE',
    label: 'Hot Rose',
    desc: 'Dark with hot-pink neon. Bold and unapologetic.',
    font: "'Outfit', sans-serif",
    bg: '#0d040a',
    border: '#cc2277',
    wordColor: '#ff3399',
    wordGlow: '0 0 18px #ff3399, 0 0 40px #aa1155',
    subColor: 'rgba(255,51,153,0.5)',
  },
  {
    num: 5,
    id: 'theme-lavender',
    tier: 'A',
    name: 'LAVENDER',
    label: 'Soft Violet',
    desc: 'Dark purple haze. Elegant and mysterious.',
    font: "'Josefin Sans', sans-serif",
    bg: '#080612',
    border: '#6633bb',
    wordColor: '#aa77ff',
    wordGlow: '0 0 15px #aa77ff, 0 0 30px #7744cc',
    subColor: 'rgba(170,119,255,0.4)',
  },
  {
    num: 6,
    id: 'theme-arctic',
    tier: 'A',
    name: 'ARCTIC',
    label: 'Icy Blue',
    desc: 'Crisp light sky background. Cool and clean.',
    font: "'Inter', sans-serif",
    bg: '#eaf4fc',
    border: '#5599cc',
    wordColor: '#1a4d7a',
    wordGlow: undefined,
    subColor: '#5599cc',
  },
  {
    num: 22,
    id: 'theme-sakura',
    tier: 'A',
    name: 'SAKURA',
    label: 'Cherry Blossom',
    desc: 'Light pink petals. Soft romantic spring.',
    font: "'Josefin Sans', sans-serif",
    bg: '#fbeef5',
    border: '#d48a9e',
    wordColor: '#7a2d4e',
    wordGlow: undefined,
    subColor: '#c4708a',
  },
  {
    num: 7,
    id: 'theme-ember',
    tier: 'B',
    name: 'EMBER',
    label: 'Ember Glow',
    desc: 'Dark warmth with amber fire. Intense and inviting.',
    font: "'Outfit', sans-serif",
    bg: '#0a0602',
    border: '#cc7700',
    wordColor: '#ffaa22',
    wordGlow: '0 0 20px #ffaa22, 0 0 45px #bb6600',
    subColor: 'rgba(255,170,34,0.5)',
  },
  {
    num: 8,
    id: 'theme-crimson',
    tier: 'B',
    name: 'CRIMSON',
    label: 'Dark Crimson',
    desc: 'Near-black with deep red power. Condensed and bold.',
    font: "'Bebas Neue', sans-serif",
    bg: '#080202',
    border: '#880000',
    wordColor: '#dd2222',
    wordGlow: '0 0 20px #dd2222, 0 0 50px #880000',
    subColor: 'rgba(221,34,34,0.5)',
  },
  {
    num: 9,
    id: 'theme-sand',
    tier: 'B',
    name: 'SAND/GOLD',
    label: 'Sand & Gold',
    desc: 'Warm parchment. Luxury language institute serif.',
    font: "'Playfair Display', serif",
    bg: '#f5efe0',
    border: '#8B6914',
    wordColor: '#6b4f0f',
    wordGlow: undefined,
    subColor: '#a07820',
  },
  {
    num: 10,
    id: 'theme-eink',
    tier: 'B',
    name: 'E-INK',
    label: 'E-Ink Minimal',
    desc: 'Pure white, zero decoration. Premium reader aesthetic.',
    font: "'Inter', sans-serif",
    bg: '#ffffff',
    border: '#e0e0e0',
    wordColor: '#111111',
    wordGlow: undefined,
    subColor: '#666666',
  },
  {
    num: 11,
    id: 'theme-phantom',
    tier: 'B',
    name: 'PHANTOM',
    label: 'Ghost Grey',
    desc: 'Dark charcoal with silver text. Understated elegance.',
    font: "'Josefin Sans', sans-serif",
    bg: '#0c0d10',
    border: '#333a44',
    wordColor: '#cccccc',
    wordGlow: '0 0 12px rgba(255,255,255,0.35)',
    subColor: '#888888',
  },
  {
    num: 12,
    id: 'theme-typewriter',
    tier: 'B',
    name: 'MONO TYPE',
    label: 'Typewriter',
    desc: 'Cream paper. The satisfying clack of keys.',
    font: "'Special Elite', cursive",
    bg: '#f0ead8',
    border: '#bba882',
    wordColor: '#2e1f0e',
    wordGlow: undefined,
    subColor: '#7a6040',
  },
  {
    num: 23,
    id: 'theme-forest',
    tier: 'B',
    name: 'FOREST',
    label: 'Woodland Deep',
    desc: 'Dark forest green. Rich earthy moss tones.',
    font: "'DM Serif Display', serif",
    bg: '#060f06',
    border: '#1a4a1a',
    wordColor: '#66ee66',
    wordGlow: '0 0 15px #44cc44, 0 0 35px #228822',
    subColor: 'rgba(102,238,102,0.45)',
  },
  {
    num: 13,
    id: 'theme-abyss',
    tier: 'C',
    name: 'ABYSS',
    label: 'Abyssal Navy',
    desc: 'Deep navy with Orbitron tech. Space station terminal.',
    font: "'Orbitron', sans-serif",
    bg: '#020510',
    border: '#1a3880',
    wordColor: '#6699ff',
    wordGlow: '0 0 25px #6699ff, 0 0 55px #334499',
    subColor: 'rgba(102,153,255,0.5)',
  },
  {
    num: 14,
    id: 'theme-espresso',
    tier: 'C',
    name: 'ESPRESSO',
    label: 'Dark Coffee',
    desc: 'Warm dark brown. Rich roasted tones.',
    font: "'Playfair Display', serif",
    bg: '#080402',
    border: '#664422',
    wordColor: '#cc8844',
    wordGlow: '0 0 15px #cc8844',
    subColor: 'rgba(204,136,68,0.5)',
  },
  {
    num: 15,
    id: 'theme-cosmos',
    tier: 'C',
    name: 'COSMOS',
    label: 'Constellation',
    desc: 'Starfield dark. Navigate by the stars.',
    font: "'Josefin Sans', sans-serif",
    bg: '#020309',
    border: '#1a2255',
    wordColor: '#88bbdd',
    wordGlow: '0 0 20px #88bbdd, 0 0 50px #3355aa',
    subColor: 'rgba(136,187,221,0.4)',
  },
  {
    num: 16,
    id: 'theme-electric',
    tier: 'C',
    name: 'ELECTRIC',
    label: 'Electric Blue',
    desc: 'Vivid electric blue background. Pure energy.',
    font: "'Bebas Neue', sans-serif",
    bg: '#0055cc',
    border: '#3388ff',
    wordColor: '#ffffff',
    wordGlow: '0 0 20px rgba(255,255,255,0.6)',
    subColor: 'rgba(255,255,255,0.7)',
  },
  {
    num: 17,
    id: 'theme-chalk',
    tier: 'C',
    name: 'CHALK',
    label: 'Chalk White',
    desc: 'Soft off-white. Clean and intentional.',
    font: "'Inter', sans-serif",
    bg: '#f4f5f7',
    border: '#c8cdd6',
    wordColor: '#1a2035',
    wordGlow: undefined,
    subColor: '#6677aa',
  },
  {
    num: 18,
    id: 'theme-onyx',
    tier: 'C',
    name: 'ONYX',
    label: 'Onyx Texture',
    desc: 'Ultra-dark charcoal with subtle grain. Premium dark.',
    font: "'Outfit', sans-serif",
    bg: '#0c0d0f',
    border: '#222428',
    wordColor: '#e0e2e6',
    wordGlow: '0 0 10px rgba(255,255,255,0.15)',
    subColor: 'rgba(224,226,230,0.45)',
  },
  {
    num: 24,
    id: 'theme-midnight',
    tier: 'C',
    name: 'MIDNIGHT',
    label: 'Midnight Gold',
    desc: 'Deep navy with golden stars. Regal and vast.',
    font: "'Unbounded', sans-serif",
    bg: '#040612',
    border: '#223388',
    wordColor: '#ffcc33',
    wordGlow: '0 0 25px #ffcc33, 0 0 50px #cc8800',
    subColor: 'rgba(255,204,51,0.45)',
  },
  {
    num: 25,
    id: 'theme-steel',
    tier: 'C',
    name: 'STEEL',
    label: 'Industrial Steel',
    desc: 'Blue-grey industrial. Sharp utilitarian design.',
    font: "'Barlow Condensed', sans-serif",
    bg: '#0d1014',
    border: '#2a333d',
    wordColor: '#b0c4d8',
    wordGlow: '0 0 12px rgba(176,196,216,0.3)',
    subColor: 'rgba(176,196,216,0.5)',
  },
  {
    num: 19,
    id: 'theme-aurora',
    tier: 'D',
    name: 'AURORA',
    label: 'Aurora Drift',
    desc: 'Animated green aurora. Living gradient glow.',
    font: "'Outfit', sans-serif",
    bg: '#020c04',
    border: '#116622',
    wordColor: '#44ff88',
    wordGlow: '0 0 25px #44ff88, 0 0 60px #22cc55',
    subColor: 'rgba(68,255,136,0.45)',
  },
  {
    num: 20,
    id: 'theme-nebula',
    tier: 'D',
    name: 'NEBULA',
    label: 'Nebula Drift',
    desc: 'Teal-purple animated drift. Deep space wonder.',
    font: "'Orbitron', sans-serif",
    bg: '#04020d',
    border: '#2a1155',
    wordColor: '#22ddcc',
    wordGlow: '0 0 30px #22ddcc, 0 0 70px #7733cc',
    subColor: 'rgba(34,221,204,0.4)',
  },
  {
    num: 21,
    id: 'theme-chrome',
    tier: 'D',
    name: '·TRES·',
    label: 'Chrome',
    desc: 'Metallic silver holographic. Mirror-finish.',
    font: "'Bebas Neue', sans-serif",
    bg: '#0e1014',
    border: '#44494f',
    wordColor: '#d0d4da',
    wordGlow: '0 0 10px rgba(255,255,255,0.4), 0 2px 0 rgba(0,0,0,0.5)',
    subColor: 'rgba(200,205,212,0.5)',
  },
  {
    num: 26,
    id: 'theme-horizon',
    tier: 'D',
    name: 'HORIZON',
    label: 'Sunset Drift',
    desc: 'Animated sunset gradient. Warm crimson to gold.',
    font: "'DM Serif Display', serif",
    bg: '#080305',
    border: '#772233',
    wordColor: '#ff8844',
    wordGlow: '0 0 25px #ff8844, 0 0 60px #dd2244',
    subColor: 'rgba(255,136,68,0.45)',
  },
  {
    num: 27,
    id: 'theme-cyberwave',
    tier: 'D',
    name: 'WAVER',
    label: 'Cyberwave',
    desc: 'Animated cyberpunk wave. Glitch neon energy.',
    font: "'Unbounded', sans-serif",
    bg: '#08020e',
    border: '#552299',
    wordColor: '#cc44ff',
    wordGlow: '0 0 20px #cc44ff, 0 0 50px #ff2277, 0 0 80px #6622cc',
    subColor: 'rgba(204,68,255,0.45)',
  },
  {
    num: 28,
    id: 'theme-ocean',
    tier: 'D',
    name: 'OCEAN',
    label: 'Deep Ocean',
    desc: 'Animated deep ocean wave. Teal and cobalt.',
    font: "'Josefin Sans', sans-serif",
    bg: '#030a0e',
    border: '#115566',
    wordColor: '#33dddd',
    wordGlow: '0 0 25px #33dddd, 0 0 60px #2255cc',
    subColor: 'rgba(51,221,221,0.4)',
  },
  {
    num: 29,
    id: 'theme-embers',
    tier: 'D',
    name: 'EMBERS',
    label: 'Glowing Embers',
    desc: 'Animated ember pulse. Fire and charcoal.',
    font: "'Playfair Display', serif",
    bg: '#070303',
    border: '#662211',
    wordColor: '#ff6633',
    wordGlow: '0 0 20px #ff6633, 0 0 50px #cc2200',
    subColor: 'rgba(255,102,51,0.5)',
  },
  {
    num: 30,
    id: 'theme-flamenco',
    tier: 'E',
    name: 'FLAMENCO',
    label: 'Flamenco (es)',
    desc: 'Spanish spirit — warm gold, red lace, passionate.',
    font: "'Playfair Display', serif",
    bg: '#0a0404',
    border: '#992233',
    wordColor: '#ee4455',
    wordGlow: '0 0 20px #ee4455, 0 0 45px #cc8800',
    subColor: 'rgba(238,68,85,0.5)',
  },
  {
    num: 31,
    id: 'theme-wabi',
    tier: 'E',
    name: 'WABI',
    label: 'Wabi-Sabi (ja)',
    desc: 'Japanese zen — ink wash, washi paper, imperfection.',
    font: "'Noto Sans JP', sans-serif",
    bg: '#efece6',
    border: '#b8b0a2',
    wordColor: '#2c2418',
    wordGlow: undefined,
    subColor: '#8a7e6b',
  },
  {
    num: 32,
    id: 'theme-ultimate',
    tier: 'F',
    name: 'ULTIMATE',
    label: 'Liquid Glass',
    desc: 'Liquid glass · glitch FX · Apple precision · Ultimate tier.',
    font: "'Major Mono Display', monospace",
    bg: '#0a0a0f',
    border: '#00eecc',
    wordColor: '#00ffdd',
    wordGlow: '0 0 25px #00ffdd, 0 0 60px #00eecc, 0 0 100px #005555',
    subColor: 'rgba(0,255,221,0.5)',
  },
  {
    num: 33,
    id: 'theme-acid-rain',
    tier: 'G',
    name: 'ACID RAIN',
    label: 'Acid Rain',
    desc: 'Corroded green rain on soot. Everything is dissolving.',
    font: "'Space Mono', monospace",
    bg: '#080c08',
    border: '#097000',
    wordColor: '#4cff4c',
    wordGlow: '0 0 22px #4cff4c, 0 0 52px #00aa22',
    subColor: '#15ff008c',
  },
  {
    num: 34,
    id: 'theme-vaporwave',
    tier: 'G',
    name: 'VAPORWAVE',
    label: 'Vapor Dream',
    desc: 'Sun-bleached mall aesthetic. Pink grid to the horizon.',
    font: "'Outfit', sans-serif",
    bg: '#170c1d',
    border: '#d6008f',
    wordColor: '#ff71ce',
    wordGlow: '0 0 22px #ff71ce, 0 0 52px #01cdfe',
    subColor: '#ff66cc8c',
  },
  {
    num: 35,
    id: 'theme-blacklight',
    tier: 'G',
    name: 'BLACKLIGHT',
    label: 'Blacklight',
    desc: 'UV wash on a dark room. Everything fluoresces.',
    font: "'Rajdhani', sans-serif",
    bg: '#0c0712',
    border: '#7700cc',
    wordColor: '#b388ff',
    wordGlow: '0 0 22px #b388ff, 0 0 52px #7c4dff',
    subColor: '#bb5cff8c',
  },
  {
    num: 36,
    id: 'theme-magma',
    tier: 'G',
    name: 'MAGMA',
    label: 'Magma Core',
    desc: 'Molten rock under pressure. Cracks of orange light.',
    font: "'Outfit', sans-serif",
    bg: '#120a07',
    border: '#8a2e00',
    wordColor: '#ff5722',
    wordGlow: '0 0 22px #ff5722, 0 0 52px #ff9100',
    subColor: '#ff661a8c',
  },
  {
    num: 37,
    id: 'theme-radioactive',
    tier: 'G',
    name: 'RADIOACTIVE',
    label: 'Radioactive',
    desc: 'Hazard yellow on containment black. Do not linger.',
    font: "'Space Mono', monospace",
    bg: '#0f0f0a',
    border: '#7a7600',
    wordColor: '#e8ff00',
    wordGlow: '0 0 22px #e8ff00, 0 0 52px #aacc00',
    subColor: '#fff70a8c',
  },
  {
    num: 38,
    id: 'theme-bubblegum',
    tier: 'G',
    name: 'BUBBLEGUM',
    label: 'Bubblegum',
    desc: 'Chewed-pink sugar rush. Loud and unrepentant.',
    font: "'Outfit', sans-serif",
    bg: '#22111a',
    border: '#d60059',
    wordColor: '#ff4fa3',
    wordGlow: '0 0 22px #ff4fa3, 0 0 52px #ff9ecb',
    subColor: '#ff66a68c',
  },
  {
    num: 39,
    id: 'theme-oil-slick',
    tier: 'G',
    name: 'OIL SLICK',
    label: 'Oil Slick',
    desc: 'Iridescent film on black water. Shifts as you move.',
    font: "'Rajdhani', sans-serif",
    bg: '#07070d',
    border: '#630da0',
    wordColor: '#8f6dff',
    wordGlow: '0 0 22px #8f6dff, 0 0 52px #22d3b8',
    subColor: '#ac4cf08c',
  },
  {
    num: 40,
    id: 'theme-infrared',
    tier: 'G',
    name: 'INFRARED',
    label: 'Infrared',
    desc: 'Thermal bloom. Heat signatures in the dark.',
    font: "'Space Mono', monospace",
    bg: '#0e0606',
    border: '#8a0000',
    wordColor: '#ff2d2d',
    wordGlow: '0 0 22px #ff2d2d, 0 0 52px #8b0000',
    subColor: '#ff1a1a8c',
  },
  {
    num: 41,
    id: 'theme-plasma',
    tier: 'G',
    name: 'PLASMA',
    label: 'Plasma Arc',
    desc: 'Contained lightning. Magenta discharge on blue.',
    font: "'Rajdhani', sans-serif",
    bg: '#090613',
    border: '#ad00bd',
    wordColor: '#e040fb',
    wordGlow: '0 0 22px #e040fb, 0 0 52px #2979ff',
    subColor: '#f04dff8c',
  },
  {
    num: 42,
    id: 'theme-solar-flare',
    tier: 'G',
    name: 'SOLAR FLARE',
    label: 'Solar Flare',
    desc: 'White-hot corona. Too bright to look at directly.',
    font: "'Outfit', sans-serif",
    bg: '#0f0b05',
    border: '#996600',
    wordColor: '#ffb300',
    wordGlow: '0 0 22px #ffb300, 0 0 52px #ff6d00',
    subColor: '#ffb8298c',
  },
  {
    num: 43,
    id: 'theme-glitch',
    tier: 'G',
    name: 'GLITCH',
    label: 'Signal Glitch',
    desc: 'Torn signal. Channels bleeding into each other.',
    font: "'Space Mono', monospace",
    bg: '#080808',
    border: '#a30029',
    wordColor: '#ff0055',
    wordGlow: '0 0 22px #ff0055, 0 0 52px #00fff0',
    subColor: '#ff33668c',
  },
  {
    num: 44,
    id: 'theme-toxic-slime',
    tier: 'G',
    name: 'TOXIC SLIME',
    label: 'Toxic Slime',
    desc: 'Dripping lime sludge. Faintly luminous.',
    font: "'Outfit', sans-serif",
    bg: '#0b1109',
    border: '#2f7000',
    wordColor: '#aaff00',
    wordGlow: '0 0 22px #aaff00, 0 0 52px #00ff88',
    subColor: '#6aff008c',
  },
  {
    num: 45,
    id: 'theme-deep-sea',
    tier: 'G',
    name: 'DEEP SEA',
    label: 'Abyssal Bloom',
    desc: 'Bioluminescence at crushing depth. Nothing else glows.',
    font: "'Rajdhani', sans-serif",
    bg: '#040c10',
    border: '#007070',
    wordColor: '#00e5c0',
    wordGlow: '0 0 22px #00e5c0, 0 0 52px #0066ff',
    subColor: '#00ffff8c',
  },
  {
    num: 46,
    id: 'theme-supernova',
    tier: 'G',
    name: 'SUPERNOVA',
    label: 'Supernova',
    desc: 'A star coming apart. Gold shockfront on void.',
    font: "'Outfit', sans-serif",
    bg: '#05060b',
    border: '#ad8b00',
    wordColor: '#ffd54f',
    wordGlow: '0 0 22px #ffd54f, 0 0 52px #b388ff',
    subColor: '#ffd83d8c',
  },
  {
    num: 47,
    id: 'theme-venom',
    tier: 'G',
    name: 'VENOM',
    label: 'Venom',
    desc: 'Purple toxin, green antivenom. Pick one.',
    font: "'Rajdhani', sans-serif",
    bg: '#0b050f',
    border: '#8200ad',
    wordColor: '#a855f7',
    wordGlow: '0 0 22px #a855f7, 0 0 52px #39ff14',
    subColor: '#cf3dff8c',
  },
  {
    num: 48,
    id: 'theme-hologram',
    tier: 'G',
    name: 'HOLOGRAM',
    label: 'Hologram',
    desc: 'Projected light with no substance. Flickers at the edges.',
    font: "'Space Mono', monospace",
    bg: '#061013',
    border: '#0096a3',
    wordColor: '#5ce1e6',
    wordGlow: '0 0 22px #5ce1e6, 0 0 52px #ff6ec7',
    subColor: '#33eeff8c',
  },
  {
    num: 49,
    id: 'theme-inferno',
    tier: 'G',
    name: 'INFERNO',
    label: 'Inferno',
    desc: 'Full burn. Orange tongues on charcoal.',
    font: "'Outfit', sans-serif",
    bg: '#0a0705',
    border: '#7a3300',
    wordColor: '#ff6b00',
    wordGlow: '0 0 22px #ff6b00, 0 0 52px #ff1744',
    subColor: '#ff700a8c',
  },
  {
    num: 50,
    id: 'theme-cotton-candy',
    tier: 'G',
    name: 'COTTON CANDY',
    label: 'Cotton Candy',
    desc: 'Spun pastel floss. Sweet enough to hurt.',
    font: "'Outfit', sans-serif",
    bg: '#1e101e',
    border: '#f20da6',
    wordColor: '#ffb3de',
    wordGlow: '0 0 22px #ffb3de, 0 0 52px #b3e5ff',
    subColor: '#f994d88c',
  },
  {
    num: 51,
    id: 'theme-circuit',
    tier: 'G',
    name: 'CIRCUIT',
    label: 'Circuit Board',
    desc: 'Etched traces and gold pads. Solder-mask green.',
    font: "'Space Mono', monospace",
    bg: '#07120d',
    border: '#045225',
    wordColor: '#2fd96f',
    wordGlow: '0 0 22px #2fd96f, 0 0 52px #ffc107',
    subColor: '#0bda628c',
  },
  {
    num: 52,
    id: 'theme-eclipse',
    tier: 'G',
    name: 'ECLIPSE',
    label: 'Total Eclipse',
    desc: 'Blacked-out disc, corona burning around the rim.',
    font: "'Rajdhani', sans-serif",
    bg: '#050505',
    border: '#9f6b04',
    wordColor: '#ffca28',
    wordGlow: '0 0 22px #ffca28, 0 0 52px #ffffff',
    subColor: '#fab9388c',
  },
];
