export interface WordEntry {
  word: string;
  translation: string;
  index: number;
  pronunciation?: string;
}

export interface LanguageData {
  code: string;
  name: string;
  categories: string[];
}

export const FALLBACK_LANGUAGES: LanguageData[] = [
  { code: 'es', name: 'Spanish', categories: ['numbers', 'colors', 'greetings', 'animals', 'food'] },
  { code: 'fr', name: 'French', categories: ['numbers', 'colors', 'greetings', 'animals', 'food'] },
  { code: 'it', name: 'Italian', categories: ['numbers', 'colors', 'greetings', 'animals', 'food'] },
  { code: 'de', name: 'German', categories: ['numbers', 'colors', 'greetings', 'animals', 'food'] },
  { code: 'ja', name: 'Japanese', categories: ['numbers', 'colors', 'greetings', 'animals', 'food'] },
  { code: 'ko', name: 'Korean', categories: ['numbers', 'colors', 'greetings', 'animals', 'food'] },
  { code: 'pt', name: 'Portuguese', categories: ['numbers', 'colors', 'greetings', 'animals', 'food'] },
  { code: 'zh', name: 'Chinese', categories: ['numbers', 'colors', 'greetings', 'animals', 'food'] },
  { code: 'ru', name: 'Russian', categories: ['numbers', 'colors', 'greetings', 'animals', 'food'] },
  { code: 'ar', name: 'Arabic', categories: ['numbers', 'colors', 'greetings', 'animals', 'food'] },
  { code: 'hi', name: 'Hindi', categories: ['numbers', 'colors', 'greetings', 'animals', 'food'] },
  { code: 'nl', name: 'Dutch', categories: ['numbers', 'colors', 'greetings', 'animals', 'food'] },
  { code: 'pl', name: 'Polish', categories: ['numbers', 'colors', 'greetings', 'animals', 'food'] },
  { code: 'sv', name: 'Swedish', categories: ['numbers', 'colors', 'greetings', 'animals', 'food'] },
  { code: 'tr', name: 'Turkish', categories: ['numbers', 'colors', 'greetings', 'animals', 'food'] },
  { code: 'th', name: 'Thai', categories: ['numbers', 'colors', 'greetings', 'animals', 'food'] },
  { code: 'vi', name: 'Vietnamese', categories: ['numbers', 'colors', 'greetings', 'animals', 'food'] },
];

export function normalizeLanguagesData(value: unknown): LanguageData[] {
  if (Array.isArray(value)) {
    return value.filter(
      (item): item is LanguageData =>
        typeof item === 'object' && item !== null && 'code' in item && 'name' in item,
    );
  }

  if (value && typeof value === 'object') {
    const maybeLanguages = (value as { languages?: unknown }).languages;
    if (Array.isArray(maybeLanguages)) {
      return maybeLanguages.filter(
        (item): item is LanguageData =>
          typeof item === 'object' && item !== null && 'code' in item && 'name' in item,
      );
    }
  }

  return FALLBACK_LANGUAGES;
}

export const FALLBACK_WORDS: Record<string, Record<string, WordEntry[]>> = {
  es: {
    numbers: [
      { word: 'uno', translation: 'one', index: 0 },
      { word: 'dos', translation: 'two', index: 1 },
      { word: 'tres', translation: 'three', index: 2 },
      { word: 'cuatro', translation: 'four', index: 3 },
      { word: 'cinco', translation: 'five', index: 4 },
      { word: 'seis', translation: 'six', index: 5 },
      { word: 'siete', translation: 'seven', index: 6 },
      { word: 'ocho', translation: 'eight', index: 7 },
      { word: 'nueve', translation: 'nine', index: 8 },
      { word: 'diez', translation: 'ten', index: 9 },
      { word: 'once', translation: 'eleven', index: 10 },
      { word: 'doce', translation: 'twelve', index: 11 },
      { word: 'trece', translation: 'thirteen', index: 12 },
      { word: 'catorce', translation: 'fourteen', index: 13 },
      { word: 'quince', translation: 'fifteen', index: 14 },
      { word: 'dieciséis', translation: 'sixteen', index: 15 },
      { word: 'diecisiete', translation: 'seventeen', index: 16 },
      { word: 'dieciocho', translation: 'eighteen', index: 17 },
      { word: 'diecinueve', translation: 'nineteen', index: 18 },
      { word: 'veinte', translation: 'twenty', index: 19 },
    ],
    colors: [
      { word: 'rojo', translation: 'red', index: 0, pronunciation: 'ROH-hoh' },
      { word: 'azul', translation: 'blue', index: 1, pronunciation: 'ah-SOOL' },
      { word: 'verde', translation: 'green', index: 2, pronunciation: 'BEHR-deh' },
      { word: 'amarillo', translation: 'yellow', index: 3, pronunciation: 'ah-mah-REE-yoh' },
      { word: 'negro', translation: 'black', index: 4, pronunciation: 'NEH-groh' },
      { word: 'blanco', translation: 'white', index: 5, pronunciation: 'BLAHN-koh' },
      { word: 'naranja', translation: 'orange', index: 6, pronunciation: 'nah-RAHN-hah' },
      { word: 'morado', translation: 'purple', index: 7, pronunciation: 'moh-RAH-doh' },
      { word: 'rosa', translation: 'pink', index: 8, pronunciation: 'ROH-sah' },
      { word: 'gris', translation: 'grey', index: 9, pronunciation: 'grees' },
    ],
    greetings: [
      { word: 'hola', translation: 'hello', index: 0, pronunciation: 'OH-lah' },
      { word: 'adiós', translation: 'goodbye', index: 1, pronunciation: 'ah-DYOHS' },
      { word: 'gracias', translation: 'thank you', index: 2, pronunciation: 'GRAH-syahs' },
      { word: 'por favor', translation: 'please', index: 3, pronunciation: 'por fah-VOR' },
      { word: 'sí', translation: 'yes', index: 4, pronunciation: 'see' },
      { word: 'no', translation: 'no', index: 5, pronunciation: 'noh' },
      { word: 'buenos días', translation: 'good morning', index: 6, pronunciation: 'BWEH-nohs DEE-ahs' },
      { word: 'buenas noches', translation: 'good night', index: 7, pronunciation: 'BWEH-nahs NOH-chehs' },
      { word: 'perdón', translation: 'excuse me', index: 8, pronunciation: 'pehr-DOHN' },
      { word: '¿cómo estás?', translation: 'how are you?', index: 9, pronunciation: 'KOH-moh ehs-TAHS' },
    ],
    animals: [
      { word: 'perro', translation: 'dog', index: 0, pronunciation: 'PEH-rroh' },
      { word: 'gato', translation: 'cat', index: 1, pronunciation: 'GAH-toh' },
      { word: 'pájaro', translation: 'bird', index: 2, pronunciation: 'PAH-hah-roh' },
      { word: 'pez', translation: 'fish', index: 3, pronunciation: 'pehs' },
      { word: 'caballo', translation: 'horse', index: 4, pronunciation: 'kah-BAH-yoh' },
      { word: 'vaca', translation: 'cow', index: 5, pronunciation: 'BAH-kah' },
      { word: 'oso', translation: 'bear', index: 6, pronunciation: 'OH-soh' },
      { word: 'lobo', translation: 'wolf', index: 7, pronunciation: 'LOH-boh' },
    ],
    food: [
      { word: 'pan', translation: 'bread', index: 0, pronunciation: 'pahn' },
      { word: 'agua', translation: 'water', index: 1, pronunciation: 'AH-gwah' },
      { word: 'leche', translation: 'milk', index: 2, pronunciation: 'LEH-cheh' },
      { word: 'manzana', translation: 'apple', index: 3, pronunciation: 'mahn-SAH-nah' },
      { word: 'arroz', translation: 'rice', index: 4, pronunciation: 'ah-RROHS' },
      { word: 'queso', translation: 'cheese', index: 5, pronunciation: 'KEH-soh' },
      { word: 'café', translation: 'coffee', index: 6, pronunciation: 'kah-FEH' },
      { word: 'huevo', translation: 'egg', index: 7, pronunciation: 'WEH-boh' },
    ],
  },
  fr: {
    numbers: [
      { word: 'un', translation: 'one', index: 0 },
      { word: 'deux', translation: 'two', index: 1 },
      { word: 'trois', translation: 'three', index: 2 },
      { word: 'quatre', translation: 'four', index: 3 },
      { word: 'cinq', translation: 'five', index: 4 },
      { word: 'six', translation: 'six', index: 5 },
      { word: 'sept', translation: 'seven', index: 6 },
      { word: 'huit', translation: 'eight', index: 7 },
      { word: 'neuf', translation: 'nine', index: 8 },
      { word: 'dix', translation: 'ten', index: 9 },
      { word: 'onze', translation: 'eleven', index: 10 },
      { word: 'douze', translation: 'twelve', index: 11 },
      { word: 'treize', translation: 'thirteen', index: 12 },
      { word: 'quatorze', translation: 'fourteen', index: 13 },
      { word: 'quinze', translation: 'fifteen', index: 14 },
      { word: 'seize', translation: 'sixteen', index: 15 },
      { word: 'dix-sept', translation: 'seventeen', index: 16 },
      { word: 'dix-huit', translation: 'eighteen', index: 17 },
      { word: 'dix-neuf', translation: 'nineteen', index: 18 },
      { word: 'vingt', translation: 'twenty', index: 19 },
    ],
    colors: [
      { word: 'rouge', translation: 'red', index: 0, pronunciation: 'roozh' },
      { word: 'bleu', translation: 'blue', index: 1, pronunciation: 'bluh' },
      { word: 'vert', translation: 'green', index: 2, pronunciation: 'vehr' },
      { word: 'jaune', translation: 'yellow', index: 3, pronunciation: 'zhohn' },
      { word: 'noir', translation: 'black', index: 4, pronunciation: 'nwahr' },
      { word: 'blanc', translation: 'white', index: 5, pronunciation: 'blahn' },
      { word: 'orange', translation: 'orange', index: 6, pronunciation: 'oh-RAHNZH' },
      { word: 'violet', translation: 'purple', index: 7, pronunciation: 'vyoh-LEH' },
      { word: 'rose', translation: 'pink', index: 8, pronunciation: 'rohz' },
      { word: 'gris', translation: 'grey', index: 9, pronunciation: 'gree' },
    ],
    greetings: [
      { word: 'salut', translation: 'hello', index: 0, pronunciation: 'sah-LEW' },
      { word: 'au revoir', translation: 'goodbye', index: 1, pronunciation: 'oh ruh-VWAHR' },
      { word: 'merci', translation: 'thank you', index: 2, pronunciation: 'mehr-SEE' },
      { word: 's\'il vous plaît', translation: 'please', index: 3, pronunciation: 'seel voo PLEH' },
      { word: 'oui', translation: 'yes', index: 4, pronunciation: 'wee' },
      { word: 'non', translation: 'no', index: 5, pronunciation: 'nohn' },
      { word: 'bonjour', translation: 'good morning', index: 6, pronunciation: 'bohn-ZHOOR' },
      { word: 'bonne nuit', translation: 'good night', index: 7, pronunciation: 'bun NWEE' },
      { word: 'excusez-moi', translation: 'excuse me', index: 8, pronunciation: 'ehk-skew-zay MWAH' },
      { word: 'comment allez-vous?', translation: 'how are you?', index: 9, pronunciation: 'koh-mahn tah-lay VOO' },
    ],
    animals: [
      { word: 'chien', translation: 'dog', index: 0, pronunciation: 'shyan' },
      { word: 'chat', translation: 'cat', index: 1, pronunciation: 'shah' },
      { word: 'oiseau', translation: 'bird', index: 2, pronunciation: 'wah-ZOH' },
      { word: 'poisson', translation: 'fish', index: 3, pronunciation: 'pwah-SOHN' },
      { word: 'cheval', translation: 'horse', index: 4, pronunciation: 'shuh-VAHL' },
      { word: 'vache', translation: 'cow', index: 5, pronunciation: 'vahsh' },
      { word: 'ours', translation: 'bear', index: 6, pronunciation: 'oors' },
      { word: 'loup', translation: 'wolf', index: 7, pronunciation: 'loo' },
    ],
    food: [
      { word: 'pain', translation: 'bread', index: 0, pronunciation: 'pan' },
      { word: 'eau', translation: 'water', index: 1, pronunciation: 'oh' },
      { word: 'lait', translation: 'milk', index: 2, pronunciation: 'leh' },
      { word: 'pomme', translation: 'apple', index: 3, pronunciation: 'pum' },
      { word: 'riz', translation: 'rice', index: 4, pronunciation: 'ree' },
      { word: 'fromage', translation: 'cheese', index: 5, pronunciation: 'froh-MAHZH' },
      { word: 'café', translation: 'coffee', index: 6, pronunciation: 'kah-FEH' },
      { word: 'œuf', translation: 'egg', index: 7, pronunciation: 'uhf' },
    ],
  },
  it: {
    numbers: [
      { word: 'uno', translation: 'one', index: 0 },
      { word: 'due', translation: 'two', index: 1 },
      { word: 'tre', translation: 'three', index: 2 },
      { word: 'quattro', translation: 'four', index: 3 },
      { word: 'cinque', translation: 'five', index: 4 },
      { word: 'sei', translation: 'six', index: 5 },
      { word: 'sette', translation: 'seven', index: 6 },
      { word: 'otto', translation: 'eight', index: 7 },
      { word: 'nove', translation: 'nine', index: 8 },
      { word: 'dieci', translation: 'ten', index: 9 },
      { word: 'undici', translation: 'eleven', index: 10 },
      { word: 'dodici', translation: 'twelve', index: 11 },
      { word: 'tredici', translation: 'thirteen', index: 12 },
      { word: 'quattordici', translation: 'fourteen', index: 13 },
      { word: 'quindici', translation: 'fifteen', index: 14 },
      { word: 'sedici', translation: 'sixteen', index: 15 },
      { word: 'diciassette', translation: 'seventeen', index: 16 },
      { word: 'diciotto', translation: 'eighteen', index: 17 },
      { word: 'diciannove', translation: 'nineteen', index: 18 },
      { word: 'venti', translation: 'twenty', index: 19 },
    ],
    colors: [
      { word: 'rosso', translation: 'red', index: 0, pronunciation: 'ROHS-soh' },
      { word: 'blu', translation: 'blue', index: 1, pronunciation: 'bloo' },
      { word: 'verde', translation: 'green', index: 2, pronunciation: 'VEHR-deh' },
      { word: 'giallo', translation: 'yellow', index: 3, pronunciation: 'JAHL-loh' },
      { word: 'nero', translation: 'black', index: 4, pronunciation: 'NEH-roh' },
      { word: 'bianco', translation: 'white', index: 5, pronunciation: 'BYAHN-koh' },
      { word: 'arancione', translation: 'orange', index: 6, pronunciation: 'ah-rahn-CHOH-neh' },
      { word: 'viola', translation: 'purple', index: 7, pronunciation: 'VYOH-lah' },
      { word: 'rosa', translation: 'pink', index: 8, pronunciation: 'ROH-zah' },
      { word: 'grigio', translation: 'grey', index: 9, pronunciation: 'GREE-joh' },
    ],
    greetings: [
      { word: 'ciao', translation: 'hello', index: 0, pronunciation: 'chow' },
      { word: 'arrivederci', translation: 'goodbye', index: 1, pronunciation: 'ah-ree-veh-DEHR-chee' },
      { word: 'grazie', translation: 'thank you', index: 2, pronunciation: 'GRAH-tsyeh' },
      { word: 'per favore', translation: 'please', index: 3, pronunciation: 'pehr fah-VOH-reh' },
      { word: 'sì', translation: 'yes', index: 4, pronunciation: 'see' },
      { word: 'no', translation: 'no', index: 5, pronunciation: 'noh' },
      { word: 'buongiorno', translation: 'good morning', index: 6, pronunciation: 'bwohn-JOR-noh' },
      { word: 'buonanotte', translation: 'good night', index: 7, pronunciation: 'bwoh-nah-NOT-teh' },
      { word: 'scusi', translation: 'excuse me', index: 8, pronunciation: 'SKOO-zee' },
      { word: 'come stai?', translation: 'how are you?', index: 9, pronunciation: 'KOH-meh STAI' },
    ],
    animals: [
      { word: 'cane', translation: 'dog', index: 0, pronunciation: 'KAH-neh' },
      { word: 'gatto', translation: 'cat', index: 1, pronunciation: 'GAHT-toh' },
      { word: 'uccello', translation: 'bird', index: 2, pronunciation: 'oo-CHEL-loh' },
      { word: 'pesce', translation: 'fish', index: 3, pronunciation: 'PEH-sheh' },
      { word: 'cavallo', translation: 'horse', index: 4, pronunciation: 'kah-VAHL-loh' },
      { word: 'mucca', translation: 'cow', index: 5, pronunciation: 'MOOK-kah' },
      { word: 'orso', translation: 'bear', index: 6, pronunciation: 'OR-soh' },
      { word: 'lupo', translation: 'wolf', index: 7, pronunciation: 'LOO-poh' },
    ],
    food: [
      { word: 'pane', translation: 'bread', index: 0, pronunciation: 'PAH-neh' },
      { word: 'acqua', translation: 'water', index: 1, pronunciation: 'AHK-kwah' },
      { word: 'latte', translation: 'milk', index: 2, pronunciation: 'LAHT-teh' },
      { word: 'mela', translation: 'apple', index: 3, pronunciation: 'MEH-lah' },
      { word: 'riso', translation: 'rice', index: 4, pronunciation: 'REE-zoh' },
      { word: 'formaggio', translation: 'cheese', index: 5, pronunciation: 'for-MAHJ-joh' },
      { word: 'caffè', translation: 'coffee', index: 6, pronunciation: 'kahf-FEH' },
      { word: 'uovo', translation: 'egg', index: 7, pronunciation: 'WOH-voh' },
    ],
  },
  de: {
    numbers: [
      { word: 'eins', translation: 'one', index: 0 },
      { word: 'zwei', translation: 'two', index: 1 },
      { word: 'drei', translation: 'three', index: 2 },
      { word: 'vier', translation: 'four', index: 3 },
      { word: 'fünf', translation: 'five', index: 4 },
      { word: 'sechs', translation: 'six', index: 5 },
      { word: 'sieben', translation: 'seven', index: 6 },
      { word: 'acht', translation: 'eight', index: 7 },
      { word: 'neun', translation: 'nine', index: 8 },
      { word: 'zehn', translation: 'ten', index: 9 },
      { word: 'elf', translation: 'eleven', index: 10 },
      { word: 'zwölf', translation: 'twelve', index: 11 },
      { word: 'dreizehn', translation: 'thirteen', index: 12 },
      { word: 'vierzehn', translation: 'fourteen', index: 13 },
      { word: 'fünfzehn', translation: 'fifteen', index: 14 },
      { word: 'sechzehn', translation: 'sixteen', index: 15 },
      { word: 'siebzehn', translation: 'seventeen', index: 16 },
      { word: 'achtzehn', translation: 'eighteen', index: 17 },
      { word: 'neunzehn', translation: 'nineteen', index: 18 },
      { word: 'zwanzig', translation: 'twenty', index: 19 },
    ],
    colors: [
      { word: 'rot', translation: 'red', index: 0, pronunciation: 'roht' },
      { word: 'blau', translation: 'blue', index: 1, pronunciation: 'blau' },
      { word: 'grün', translation: 'green', index: 2, pronunciation: 'groon' },
      { word: 'gelb', translation: 'yellow', index: 3, pronunciation: 'gehlp' },
      { word: 'schwarz', translation: 'black', index: 4, pronunciation: 'shvarts' },
      { word: 'weiß', translation: 'white', index: 5, pronunciation: 'vise' },
      { word: 'orange', translation: 'orange', index: 6, pronunciation: 'oh-RAHNZH' },
      { word: 'lila', translation: 'purple', index: 7, pronunciation: 'LEE-lah' },
      { word: 'rosa', translation: 'pink', index: 8, pronunciation: 'ROH-zah' },
      { word: 'grau', translation: 'grey', index: 9, pronunciation: 'grau' },
    ],
    greetings: [
      { word: 'hallo', translation: 'hello', index: 0, pronunciation: 'HAH-loh' },
      { word: 'auf Wiedersehen', translation: 'goodbye', index: 1, pronunciation: 'owf VEE-der-zayn' },
      { word: 'danke', translation: 'thank you', index: 2, pronunciation: 'DAHN-kuh' },
      { word: 'bitte', translation: 'please', index: 3, pronunciation: 'BIT-tuh' },
      { word: 'ja', translation: 'yes', index: 4, pronunciation: 'yah' },
      { word: 'nein', translation: 'no', index: 5, pronunciation: 'nine' },
      { word: 'guten Morgen', translation: 'good morning', index: 6, pronunciation: 'GOO-ten MOR-gen' },
      { word: 'gute Nacht', translation: 'good night', index: 7, pronunciation: 'GOO-tuh nahkt' },
      { word: 'entschuldigung', translation: 'excuse me', index: 8, pronunciation: 'ent-SHOOL-di-goong' },
      { word: 'wie geht es dir?', translation: 'how are you?', index: 9, pronunciation: 'vee gayt es deer' },
    ],
    animals: [
      { word: 'Hund', translation: 'dog', index: 0, pronunciation: 'hoont' },
      { word: 'Katze', translation: 'cat', index: 1, pronunciation: 'KAHT-suh' },
      { word: 'Vogel', translation: 'bird', index: 2, pronunciation: 'FOH-gel' },
      { word: 'Fisch', translation: 'fish', index: 3, pronunciation: 'fish' },
      { word: 'Pferd', translation: 'horse', index: 4, pronunciation: 'pfehrt' },
      { word: 'Kuh', translation: 'cow', index: 5, pronunciation: 'koo' },
      { word: 'Bär', translation: 'bear', index: 6, pronunciation: 'behr' },
      { word: 'Wolf', translation: 'wolf', index: 7, pronunciation: 'volf' },
    ],
    food: [
      { word: 'Brot', translation: 'bread', index: 0, pronunciation: 'broht' },
      { word: 'Wasser', translation: 'water', index: 1, pronunciation: 'VAH-ser' },
      { word: 'Milch', translation: 'milk', index: 2, pronunciation: 'milkh' },
      { word: 'Apfel', translation: 'apple', index: 3, pronunciation: 'AHP-fel' },
      { word: 'Reis', translation: 'rice', index: 4, pronunciation: 'rice' },
      { word: 'Käse', translation: 'cheese', index: 5, pronunciation: 'KAY-zuh' },
      { word: 'Kaffee', translation: 'coffee', index: 6, pronunciation: 'KAH-fay' },
      { word: 'Ei', translation: 'egg', index: 7, pronunciation: 'eye' },
    ],
  },
  pt: {
    numbers: [
      { word: 'um', translation: 'one', index: 0 },
      { word: 'dois', translation: 'two', index: 1 },
      { word: 'três', translation: 'three', index: 2 },
      { word: 'quatro', translation: 'four', index: 3 },
      { word: 'cinco', translation: 'five', index: 4 },
      { word: 'seis', translation: 'six', index: 5 },
      { word: 'sete', translation: 'seven', index: 6 },
      { word: 'oito', translation: 'eight', index: 7 },
      { word: 'nove', translation: 'nine', index: 8 },
      { word: 'dez', translation: 'ten', index: 9 },
      { word: 'onze', translation: 'eleven', index: 10 },
      { word: 'doze', translation: 'twelve', index: 11 },
      { word: 'treze', translation: 'thirteen', index: 12 },
      { word: 'catorze', translation: 'fourteen', index: 13 },
      { word: 'quinze', translation: 'fifteen', index: 14 },
      { word: 'dezesseis', translation: 'sixteen', index: 15 },
      { word: 'dezessete', translation: 'seventeen', index: 16 },
      { word: 'dezoito', translation: 'eighteen', index: 17 },
      { word: 'dezenove', translation: 'nineteen', index: 18 },
      { word: 'vinte', translation: 'twenty', index: 19 },
    ],
    colors: [
      { word: 'vermelho', translation: 'red', index: 0, pronunciation: 'ver-MEH-lyoo' },
      { word: 'azul', translation: 'blue', index: 1, pronunciation: 'ah-ZOOL' },
      { word: 'verde', translation: 'green', index: 2, pronunciation: 'VEHR-jee' },
      { word: 'amarelo', translation: 'yellow', index: 3, pronunciation: 'ah-mah-REH-loo' },
      { word: 'preto', translation: 'black', index: 4, pronunciation: 'PREH-too' },
      { word: 'branco', translation: 'white', index: 5, pronunciation: 'BRAHN-koo' },
      { word: 'laranja', translation: 'orange', index: 6, pronunciation: 'lah-RAHN-zhah' },
      { word: 'roxo', translation: 'purple', index: 7, pronunciation: 'HOH-shoo' },
      { word: 'rosa', translation: 'pink', index: 8, pronunciation: 'HOH-zah' },
      { word: 'cinza', translation: 'grey', index: 9, pronunciation: 'SEEN-zah' },
    ],
    greetings: [
      { word: 'olá', translation: 'hello', index: 0, pronunciation: 'oh-LAH' },
      { word: 'tchau', translation: 'goodbye', index: 1, pronunciation: 'chow' },
      { word: 'obrigado', translation: 'thank you', index: 2, pronunciation: 'oh-bree-GAH-doo' },
      { word: 'por favor', translation: 'please', index: 3, pronunciation: 'poor fah-VOR' },
      { word: 'sim', translation: 'yes', index: 4, pronunciation: 'seeng' },
      { word: 'não', translation: 'no', index: 5, pronunciation: 'nowng' },
      { word: 'bom dia', translation: 'good morning', index: 6, pronunciation: 'bohng DEE-ah' },
      { word: 'boa noite', translation: 'good night', index: 7, pronunciation: 'BOH-ah NOY-chee' },
      { word: 'com licença', translation: 'excuse me', index: 8, pronunciation: 'kohng lee-SEN-sah' },
      { word: 'como vai?', translation: 'how are you?', index: 9, pronunciation: 'KOH-moo vye' },
    ],
    animals: [
      { word: 'cachorro', translation: 'dog', index: 0, pronunciation: 'kah-SHOH-hoo' },
      { word: 'gato', translation: 'cat', index: 1, pronunciation: 'GAH-too' },
      { word: 'pássaro', translation: 'bird', index: 2, pronunciation: 'PAH-sah-roo' },
      { word: 'peixe', translation: 'fish', index: 3, pronunciation: 'PAY-shee' },
      { word: 'cavalo', translation: 'horse', index: 4, pronunciation: 'kah-VAH-loo' },
      { word: 'vaca', translation: 'cow', index: 5, pronunciation: 'VAH-kah' },
      { word: 'urso', translation: 'bear', index: 6, pronunciation: 'OOR-soo' },
      { word: 'lobo', translation: 'wolf', index: 7, pronunciation: 'LOH-boo' },
    ],
    food: [
      { word: 'pão', translation: 'bread', index: 0, pronunciation: 'powng' },
      { word: 'água', translation: 'water', index: 1, pronunciation: 'AH-gwah' },
      { word: 'leite', translation: 'milk', index: 2, pronunciation: 'LAY-chee' },
      { word: 'maçã', translation: 'apple', index: 3, pronunciation: 'mah-SAHNG' },
      { word: 'arroz', translation: 'rice', index: 4, pronunciation: 'ah-HOHS' },
      { word: 'queijo', translation: 'cheese', index: 5, pronunciation: 'KAY-zhoo' },
      { word: 'café', translation: 'coffee', index: 6, pronunciation: 'kah-FEH' },
      { word: 'ovo', translation: 'egg', index: 7, pronunciation: 'OH-voo' },
    ],
  },
  nl: {
    numbers: [
      { word: 'een', translation: 'one', index: 0 },
      { word: 'twee', translation: 'two', index: 1 },
      { word: 'drie', translation: 'three', index: 2 },
      { word: 'vier', translation: 'four', index: 3 },
      { word: 'vijf', translation: 'five', index: 4 },
      { word: 'zes', translation: 'six', index: 5 },
      { word: 'zeven', translation: 'seven', index: 6 },
      { word: 'acht', translation: 'eight', index: 7 },
      { word: 'negen', translation: 'nine', index: 8 },
      { word: 'tien', translation: 'ten', index: 9 },
      { word: 'elf', translation: 'eleven', index: 10 },
      { word: 'twaalf', translation: 'twelve', index: 11 },
      { word: 'dertien', translation: 'thirteen', index: 12 },
      { word: 'veertien', translation: 'fourteen', index: 13 },
      { word: 'vijftien', translation: 'fifteen', index: 14 },
      { word: 'zestien', translation: 'sixteen', index: 15 },
      { word: 'zeventien', translation: 'seventeen', index: 16 },
      { word: 'achttien', translation: 'eighteen', index: 17 },
      { word: 'negentien', translation: 'nineteen', index: 18 },
      { word: 'twintig', translation: 'twenty', index: 19 },
    ],
    colors: [
      { word: 'rood', translation: 'red', index: 0, pronunciation: 'roht' },
      { word: 'blauw', translation: 'blue', index: 1, pronunciation: 'blau' },
      { word: 'groen', translation: 'green', index: 2, pronunciation: 'khroon' },
      { word: 'geel', translation: 'yellow', index: 3, pronunciation: 'khayl' },
      { word: 'zwart', translation: 'black', index: 4, pronunciation: 'zvart' },
      { word: 'wit', translation: 'white', index: 5, pronunciation: 'vit' },
      { word: 'oranje', translation: 'orange', index: 6, pronunciation: 'oh-RAHN-yuh' },
      { word: 'paars', translation: 'purple', index: 7, pronunciation: 'pahrs' },
      { word: 'roze', translation: 'pink', index: 8, pronunciation: 'ROH-zuh' },
      { word: 'grijs', translation: 'grey', index: 9, pronunciation: 'khrice' },
    ],
    greetings: [
      { word: 'hallo', translation: 'hello', index: 0, pronunciation: 'HAH-loh' },
      { word: 'tot ziens', translation: 'goodbye', index: 1, pronunciation: 'tot zeens' },
      { word: 'dank je', translation: 'thank you', index: 2, pronunciation: 'dahnk yuh' },
      { word: 'alsjeblieft', translation: 'please', index: 3, pronunciation: 'AHL-shuh-bleeft' },
      { word: 'ja', translation: 'yes', index: 4, pronunciation: 'yah' },
      { word: 'nee', translation: 'no', index: 5, pronunciation: 'nay' },
      { word: 'goedemorgen', translation: 'good morning', index: 6, pronunciation: 'KHOO-duh-MOR-khen' },
      { word: 'goedenacht', translation: 'good night', index: 7, pronunciation: 'KHOO-duh-nakht' },
      { word: 'pardon', translation: 'excuse me', index: 8, pronunciation: 'par-DON' },
      { word: 'hoe gaat het?', translation: 'how are you?', index: 9, pronunciation: 'hoo khaht het' },
    ],
    animals: [
      { word: 'hond', translation: 'dog', index: 0, pronunciation: 'hont' },
      { word: 'kat', translation: 'cat', index: 1, pronunciation: 'kaht' },
      { word: 'vogel', translation: 'bird', index: 2, pronunciation: 'FOH-khel' },
      { word: 'vis', translation: 'fish', index: 3, pronunciation: 'fis' },
      { word: 'paard', translation: 'horse', index: 4, pronunciation: 'pahrt' },
      { word: 'koe', translation: 'cow', index: 5, pronunciation: 'koo' },
      { word: 'beer', translation: 'bear', index: 6, pronunciation: 'bayr' },
      { word: 'wolf', translation: 'wolf', index: 7, pronunciation: 'volf' },
    ],
    food: [
      { word: 'brood', translation: 'bread', index: 0, pronunciation: 'broht' },
      { word: 'water', translation: 'water', index: 1, pronunciation: 'VAH-ter' },
      { word: 'melk', translation: 'milk', index: 2, pronunciation: 'melk' },
      { word: 'appel', translation: 'apple', index: 3, pronunciation: 'AH-pel' },
      { word: 'rijst', translation: 'rice', index: 4, pronunciation: 'rayst' },
      { word: 'kaas', translation: 'cheese', index: 5, pronunciation: 'kahs' },
      { word: 'koffie', translation: 'coffee', index: 6, pronunciation: 'KOF-fee' },
      { word: 'ei', translation: 'egg', index: 7, pronunciation: 'ay' },
    ],
  },
  sv: {
    numbers: [
      { word: 'ett', translation: 'one', index: 0 },
      { word: 'två', translation: 'two', index: 1 },
      { word: 'tre', translation: 'three', index: 2 },
      { word: 'fyra', translation: 'four', index: 3 },
      { word: 'fem', translation: 'five', index: 4 },
      { word: 'sex', translation: 'six', index: 5 },
      { word: 'sju', translation: 'seven', index: 6 },
      { word: 'åtta', translation: 'eight', index: 7 },
      { word: 'nio', translation: 'nine', index: 8 },
      { word: 'tio', translation: 'ten', index: 9 },
      { word: 'elva', translation: 'eleven', index: 10 },
      { word: 'tolv', translation: 'twelve', index: 11 },
      { word: 'tretton', translation: 'thirteen', index: 12 },
      { word: 'fjorton', translation: 'fourteen', index: 13 },
      { word: 'femton', translation: 'fifteen', index: 14 },
      { word: 'sexton', translation: 'sixteen', index: 15 },
      { word: 'sjutton', translation: 'seventeen', index: 16 },
      { word: 'arton', translation: 'eighteen', index: 17 },
      { word: 'nitton', translation: 'nineteen', index: 18 },
      { word: 'tjugo', translation: 'twenty', index: 19 },
    ],
    colors: [
      { word: 'röd', translation: 'red', index: 0, pronunciation: 'rurd' },
      { word: 'blå', translation: 'blue', index: 1, pronunciation: 'bloh' },
      { word: 'grön', translation: 'green', index: 2, pronunciation: 'grurn' },
      { word: 'gul', translation: 'yellow', index: 3, pronunciation: 'gool' },
      { word: 'svart', translation: 'black', index: 4, pronunciation: 'svart' },
      { word: 'vit', translation: 'white', index: 5, pronunciation: 'veet' },
      { word: 'orange', translation: 'orange', index: 6, pronunciation: 'oh-RAHNSH' },
      { word: 'lila', translation: 'purple', index: 7, pronunciation: 'LEE-lah' },
      { word: 'rosa', translation: 'pink', index: 8, pronunciation: 'ROH-sah' },
      { word: 'grå', translation: 'grey', index: 9, pronunciation: 'groh' },
    ],
    greetings: [
      { word: 'hej', translation: 'hello', index: 0, pronunciation: 'hay' },
      { word: 'hej då', translation: 'goodbye', index: 1, pronunciation: 'hay doh' },
      { word: 'tack', translation: 'thank you', index: 2, pronunciation: 'tahk' },
      { word: 'snälla', translation: 'please', index: 3, pronunciation: 'SNEL-lah' },
      { word: 'ja', translation: 'yes', index: 4, pronunciation: 'yah' },
      { word: 'nej', translation: 'no', index: 5, pronunciation: 'nay' },
      { word: 'god morgon', translation: 'good morning', index: 6, pronunciation: 'good MOR-ron' },
      { word: 'god natt', translation: 'good night', index: 7, pronunciation: 'good naht' },
      { word: 'ursäkta', translation: 'excuse me', index: 8, pronunciation: 'oor-SHEK-tah' },
      { word: 'hur mår du?', translation: 'how are you?', index: 9, pronunciation: 'hoor mohr doo' },
    ],
    animals: [
      { word: 'hund', translation: 'dog', index: 0, pronunciation: 'hoond' },
      { word: 'katt', translation: 'cat', index: 1, pronunciation: 'kaht' },
      { word: 'fågel', translation: 'bird', index: 2, pronunciation: 'FOH-gel' },
      { word: 'fisk', translation: 'fish', index: 3, pronunciation: 'fisk' },
      { word: 'häst', translation: 'horse', index: 4, pronunciation: 'hest' },
      { word: 'ko', translation: 'cow', index: 5, pronunciation: 'koo' },
      { word: 'björn', translation: 'bear', index: 6, pronunciation: 'byurn' },
      { word: 'varg', translation: 'wolf', index: 7, pronunciation: 'vahrg' },
    ],
    food: [
      { word: 'bröd', translation: 'bread', index: 0, pronunciation: 'brurd' },
      { word: 'vatten', translation: 'water', index: 1, pronunciation: 'VAHT-ten' },
      { word: 'mjölk', translation: 'milk', index: 2, pronunciation: 'myurlk' },
      { word: 'äpple', translation: 'apple', index: 3, pronunciation: 'EP-leh' },
      { word: 'ris', translation: 'rice', index: 4, pronunciation: 'rees' },
      { word: 'ost', translation: 'cheese', index: 5, pronunciation: 'oost' },
      { word: 'kaffe', translation: 'coffee', index: 6, pronunciation: 'KAH-feh' },
      { word: 'ägg', translation: 'egg', index: 7, pronunciation: 'eg' },
    ],
  },
  pl: {
    numbers: [
      { word: 'jeden', translation: 'one', index: 0 },
      { word: 'dwa', translation: 'two', index: 1 },
      { word: 'trzy', translation: 'three', index: 2 },
      { word: 'cztery', translation: 'four', index: 3 },
      { word: 'pięć', translation: 'five', index: 4 },
      { word: 'sześć', translation: 'six', index: 5 },
      { word: 'siedem', translation: 'seven', index: 6 },
      { word: 'osiem', translation: 'eight', index: 7 },
      { word: 'dziewięć', translation: 'nine', index: 8 },
      { word: 'dziesięć', translation: 'ten', index: 9 },
      { word: 'jedenaście', translation: 'eleven', index: 10 },
      { word: 'dwanaście', translation: 'twelve', index: 11 },
      { word: 'trzynaście', translation: 'thirteen', index: 12 },
      { word: 'czternaście', translation: 'fourteen', index: 13 },
      { word: 'piętnaście', translation: 'fifteen', index: 14 },
      { word: 'szesnaście', translation: 'sixteen', index: 15 },
      { word: 'siedemnaście', translation: 'seventeen', index: 16 },
      { word: 'osiemnaście', translation: 'eighteen', index: 17 },
      { word: 'dziewiętnaście', translation: 'nineteen', index: 18 },
      { word: 'dwadzieścia', translation: 'twenty', index: 19 },
    ],
    colors: [
      { word: 'czerwony', translation: 'red', index: 0, pronunciation: 'cher-VOH-ni' },
      { word: 'niebieski', translation: 'blue', index: 1, pronunciation: 'nyeh-BYES-kee' },
      { word: 'zielony', translation: 'green', index: 2, pronunciation: 'zhyeh-LOH-ni' },
      { word: 'żółty', translation: 'yellow', index: 3, pronunciation: 'ZHOOW-ti' },
      { word: 'czarny', translation: 'black', index: 4, pronunciation: 'CHAR-ni' },
      { word: 'biały', translation: 'white', index: 5, pronunciation: 'BYAH-wi' },
      { word: 'pomarańczowy', translation: 'orange', index: 6, pronunciation: 'po-ma-rahn-CHO-vi' },
      { word: 'fioletowy', translation: 'purple', index: 7, pronunciation: 'fyo-leh-TOH-vi' },
      { word: 'różowy', translation: 'pink', index: 8, pronunciation: 'roo-ZHOH-vi' },
      { word: 'szary', translation: 'grey', index: 9, pronunciation: 'SHAH-ri' },
    ],
    greetings: [
      { word: 'cześć', translation: 'hello', index: 0, pronunciation: 'cheshch' },
      { word: 'do widzenia', translation: 'goodbye', index: 1, pronunciation: 'do vee-DZEH-nya' },
      { word: 'dziękuję', translation: 'thank you', index: 2, pronunciation: 'jen-KOO-yeh' },
      { word: 'proszę', translation: 'please', index: 3, pronunciation: 'PROH-sheh' },
      { word: 'tak', translation: 'yes', index: 4, pronunciation: 'tahk' },
      { word: 'nie', translation: 'no', index: 5, pronunciation: 'nyeh' },
      { word: 'dzień dobry', translation: 'good morning', index: 6, pronunciation: 'jen DOH-bri' },
      { word: 'dobranoc', translation: 'good night', index: 7, pronunciation: 'do-BRAH-nots' },
      { word: 'przepraszam', translation: 'excuse me', index: 8, pronunciation: 'psheh-PRAH-shahm' },
      { word: 'jak się masz?', translation: 'how are you?', index: 9, pronunciation: 'yahk sheh mahsh' },
    ],
    animals: [
      { word: 'pies', translation: 'dog', index: 0, pronunciation: 'pyes' },
      { word: 'kot', translation: 'cat', index: 1, pronunciation: 'kot' },
      { word: 'ptak', translation: 'bird', index: 2, pronunciation: 'ptahk' },
      { word: 'ryba', translation: 'fish', index: 3, pronunciation: 'RI-bah' },
      { word: 'koń', translation: 'horse', index: 4, pronunciation: 'kohny' },
      { word: 'krowa', translation: 'cow', index: 5, pronunciation: 'KROH-vah' },
      { word: 'niedźwiedź', translation: 'bear', index: 6, pronunciation: 'nyej-VYEJ' },
      { word: 'wilk', translation: 'wolf', index: 7, pronunciation: 'vilk' },
    ],
    food: [
      { word: 'chleb', translation: 'bread', index: 0, pronunciation: 'khlep' },
      { word: 'woda', translation: 'water', index: 1, pronunciation: 'VOH-dah' },
      { word: 'mleko', translation: 'milk', index: 2, pronunciation: 'MLEH-ko' },
      { word: 'jabłko', translation: 'apple', index: 3, pronunciation: 'YAHP-ko' },
      { word: 'ryż', translation: 'rice', index: 4, pronunciation: 'rish' },
      { word: 'ser', translation: 'cheese', index: 5, pronunciation: 'sehr' },
      { word: 'kawa', translation: 'coffee', index: 6, pronunciation: 'KAH-vah' },
      { word: 'jajko', translation: 'egg', index: 7, pronunciation: 'YAI-ko' },
    ],
  },
  tr: {
    numbers: [
      { word: 'bir', translation: 'one', index: 0 },
      { word: 'iki', translation: 'two', index: 1 },
      { word: 'üç', translation: 'three', index: 2 },
      { word: 'dört', translation: 'four', index: 3 },
      { word: 'beş', translation: 'five', index: 4 },
      { word: 'altı', translation: 'six', index: 5 },
      { word: 'yedi', translation: 'seven', index: 6 },
      { word: 'sekiz', translation: 'eight', index: 7 },
      { word: 'dokuz', translation: 'nine', index: 8 },
      { word: 'on', translation: 'ten', index: 9 },
      { word: 'on bir', translation: 'eleven', index: 10 },
      { word: 'on iki', translation: 'twelve', index: 11 },
      { word: 'on üç', translation: 'thirteen', index: 12 },
      { word: 'on dört', translation: 'fourteen', index: 13 },
      { word: 'on beş', translation: 'fifteen', index: 14 },
      { word: 'on altı', translation: 'sixteen', index: 15 },
      { word: 'on yedi', translation: 'seventeen', index: 16 },
      { word: 'on sekiz', translation: 'eighteen', index: 17 },
      { word: 'on dokuz', translation: 'nineteen', index: 18 },
      { word: 'yirmi', translation: 'twenty', index: 19 },
    ],
    colors: [
      { word: 'kırmızı', translation: 'red', index: 0, pronunciation: 'kuhr-muh-ZUH' },
      { word: 'mavi', translation: 'blue', index: 1, pronunciation: 'MAH-vee' },
      { word: 'yeşil', translation: 'green', index: 2, pronunciation: 'yeh-SHEEL' },
      { word: 'sarı', translation: 'yellow', index: 3, pronunciation: 'sah-RUH' },
      { word: 'siyah', translation: 'black', index: 4, pronunciation: 'see-YAH' },
      { word: 'beyaz', translation: 'white', index: 5, pronunciation: 'beh-YAHZ' },
      { word: 'turuncu', translation: 'orange', index: 6, pronunciation: 'too-ROON-joo' },
      { word: 'mor', translation: 'purple', index: 7, pronunciation: 'mor' },
      { word: 'pembe', translation: 'pink', index: 8, pronunciation: 'PEM-beh' },
      { word: 'gri', translation: 'grey', index: 9, pronunciation: 'gree' },
    ],
    greetings: [
      { word: 'merhaba', translation: 'hello', index: 0, pronunciation: 'MEHR-hah-bah' },
      { word: 'hoşça kal', translation: 'goodbye', index: 1, pronunciation: 'HOSH-chah kahl' },
      { word: 'teşekkürler', translation: 'thank you', index: 2, pronunciation: 'teh-shek-KEWR-lehr' },
      { word: 'lütfen', translation: 'please', index: 3, pronunciation: 'LEWT-fen' },
      { word: 'evet', translation: 'yes', index: 4, pronunciation: 'EH-vet' },
      { word: 'hayır', translation: 'no', index: 5, pronunciation: 'HAH-yuhr' },
      { word: 'günaydın', translation: 'good morning', index: 6, pronunciation: 'gew-NAI-duhn' },
      { word: 'iyi geceler', translation: 'good night', index: 7, pronunciation: 'ee-YEE geh-jeh-LEHR' },
      { word: 'affedersiniz', translation: 'excuse me', index: 8, pronunciation: 'ahf-feh-DEHR-see-neez' },
      { word: 'nasılsın?', translation: 'how are you?', index: 9, pronunciation: 'NAH-suhl-suhn' },
    ],
    animals: [
      { word: 'köpek', translation: 'dog', index: 0, pronunciation: 'kur-PEK' },
      { word: 'kedi', translation: 'cat', index: 1, pronunciation: 'keh-DEE' },
      { word: 'kuş', translation: 'bird', index: 2, pronunciation: 'koosh' },
      { word: 'balık', translation: 'fish', index: 3, pronunciation: 'bah-LUHK' },
      { word: 'at', translation: 'horse', index: 4, pronunciation: 'aht' },
      { word: 'inek', translation: 'cow', index: 5, pronunciation: 'ee-NEK' },
      { word: 'ayı', translation: 'bear', index: 6, pronunciation: 'ah-YUH' },
      { word: 'kurt', translation: 'wolf', index: 7, pronunciation: 'koort' },
    ],
    food: [
      { word: 'ekmek', translation: 'bread', index: 0, pronunciation: 'ek-MEK' },
      { word: 'su', translation: 'water', index: 1, pronunciation: 'soo' },
      { word: 'süt', translation: 'milk', index: 2, pronunciation: 'sewt' },
      { word: 'elma', translation: 'apple', index: 3, pronunciation: 'el-MAH' },
      { word: 'pirinç', translation: 'rice', index: 4, pronunciation: 'pee-REENCH' },
      { word: 'peynir', translation: 'cheese', index: 5, pronunciation: 'pay-NEER' },
      { word: 'kahve', translation: 'coffee', index: 6, pronunciation: 'kah-VEH' },
      { word: 'yumurta', translation: 'egg', index: 7, pronunciation: 'yoo-moor-TAH' },
    ],
  },
  vi: {
    numbers: [
      { word: 'một', translation: 'one', index: 0 },
      { word: 'hai', translation: 'two', index: 1 },
      { word: 'ba', translation: 'three', index: 2 },
      { word: 'bốn', translation: 'four', index: 3 },
      { word: 'năm', translation: 'five', index: 4 },
      { word: 'sáu', translation: 'six', index: 5 },
      { word: 'bảy', translation: 'seven', index: 6 },
      { word: 'tám', translation: 'eight', index: 7 },
      { word: 'chín', translation: 'nine', index: 8 },
      { word: 'mười', translation: 'ten', index: 9 },
      { word: 'mười một', translation: 'eleven', index: 10 },
      { word: 'mười hai', translation: 'twelve', index: 11 },
      { word: 'mười ba', translation: 'thirteen', index: 12 },
      { word: 'mười bốn', translation: 'fourteen', index: 13 },
      { word: 'mười lăm', translation: 'fifteen', index: 14 },
      { word: 'mười sáu', translation: 'sixteen', index: 15 },
      { word: 'mười bảy', translation: 'seventeen', index: 16 },
      { word: 'mười tám', translation: 'eighteen', index: 17 },
      { word: 'mười chín', translation: 'nineteen', index: 18 },
      { word: 'hai mươi', translation: 'twenty', index: 19 },
    ],
    colors: [
      { word: 'đỏ', translation: 'red', index: 0, pronunciation: 'doh' },
      { word: 'xanh dương', translation: 'blue', index: 1, pronunciation: 'sahn zoong' },
      { word: 'xanh lá', translation: 'green', index: 2, pronunciation: 'sahn lah' },
      { word: 'vàng', translation: 'yellow', index: 3, pronunciation: 'vahng' },
      { word: 'đen', translation: 'black', index: 4, pronunciation: 'den' },
      { word: 'trắng', translation: 'white', index: 5, pronunciation: 'trahng' },
      { word: 'cam', translation: 'orange', index: 6, pronunciation: 'kahm' },
      { word: 'tím', translation: 'purple', index: 7, pronunciation: 'teem' },
      { word: 'hồng', translation: 'pink', index: 8, pronunciation: 'hohng' },
      { word: 'xám', translation: 'grey', index: 9, pronunciation: 'sahm' },
    ],
    greetings: [
      { word: 'xin chào', translation: 'hello', index: 0, pronunciation: 'sin chow' },
      { word: 'tạm biệt', translation: 'goodbye', index: 1, pronunciation: 'tahm byet' },
      { word: 'cảm ơn', translation: 'thank you', index: 2, pronunciation: 'kahm uhn' },
      { word: 'làm ơn', translation: 'please', index: 3, pronunciation: 'lahm uhn' },
      { word: 'vâng', translation: 'yes', index: 4, pronunciation: 'vuhng' },
      { word: 'không', translation: 'no', index: 5, pronunciation: 'khohng' },
      { word: 'chào buổi sáng', translation: 'good morning', index: 6, pronunciation: 'chow booy sahng' },
      { word: 'chúc ngủ ngon', translation: 'good night', index: 7, pronunciation: 'chook ngoo ngon' },
      { word: 'xin lỗi', translation: 'excuse me', index: 8, pronunciation: 'sin loy' },
      { word: 'bạn khỏe không?', translation: 'how are you?', index: 9, pronunciation: 'bahn khweh khohng' },
    ],
    animals: [
      { word: 'chó', translation: 'dog', index: 0, pronunciation: 'chaw' },
      { word: 'mèo', translation: 'cat', index: 1, pronunciation: 'meh-oh' },
      { word: 'chim', translation: 'bird', index: 2, pronunciation: 'cheem' },
      { word: 'cá', translation: 'fish', index: 3, pronunciation: 'kah' },
      { word: 'ngựa', translation: 'horse', index: 4, pronunciation: 'nguh-ah' },
      { word: 'bò', translation: 'cow', index: 5, pronunciation: 'baw' },
      { word: 'gấu', translation: 'bear', index: 6, pronunciation: 'guh-oo' },
      { word: 'sói', translation: 'wolf', index: 7, pronunciation: 'soy' },
    ],
    food: [
      { word: 'bánh mì', translation: 'bread', index: 0, pronunciation: 'bahn mee' },
      { word: 'nước', translation: 'water', index: 1, pronunciation: 'nook' },
      { word: 'sữa', translation: 'milk', index: 2, pronunciation: 'suh-ah' },
      { word: 'táo', translation: 'apple', index: 3, pronunciation: 'tao' },
      { word: 'cơm', translation: 'rice', index: 4, pronunciation: 'kuhm' },
      { word: 'phô mai', translation: 'cheese', index: 5, pronunciation: 'foh mai' },
      { word: 'cà phê', translation: 'coffee', index: 6, pronunciation: 'kah feh' },
      { word: 'trứng', translation: 'egg', index: 7, pronunciation: 'troong' },
    ],
  },
  ja: {
    numbers: [
      { word: '一', translation: 'one', index: 0, pronunciation: 'ichi' },
      { word: '二', translation: 'two', index: 1, pronunciation: 'ni' },
      { word: '三', translation: 'three', index: 2, pronunciation: 'san' },
      { word: '四', translation: 'four', index: 3, pronunciation: 'yon' },
      { word: '五', translation: 'five', index: 4, pronunciation: 'go' },
      { word: '六', translation: 'six', index: 5, pronunciation: 'roku' },
      { word: '七', translation: 'seven', index: 6, pronunciation: 'nana' },
      { word: '八', translation: 'eight', index: 7, pronunciation: 'hachi' },
      { word: '九', translation: 'nine', index: 8, pronunciation: 'kyū' },
      { word: '十', translation: 'ten', index: 9, pronunciation: 'jū' },
      { word: '十一', translation: 'eleven', index: 10, pronunciation: 'jū-ichi' },
      { word: '十二', translation: 'twelve', index: 11, pronunciation: 'jū-ni' },
      { word: '十三', translation: 'thirteen', index: 12, pronunciation: 'jū-san' },
      { word: '十四', translation: 'fourteen', index: 13, pronunciation: 'jū-yon' },
      { word: '十五', translation: 'fifteen', index: 14, pronunciation: 'jū-go' },
      { word: '十六', translation: 'sixteen', index: 15, pronunciation: 'jū-roku' },
      { word: '十七', translation: 'seventeen', index: 16, pronunciation: 'jū-nana' },
      { word: '十八', translation: 'eighteen', index: 17, pronunciation: 'jū-hachi' },
      { word: '十九', translation: 'nineteen', index: 18, pronunciation: 'jū-kyū' },
      { word: '二十', translation: 'twenty', index: 19, pronunciation: 'nijū' },
    ],
    colors: [
      { word: '赤', translation: 'red', index: 0, pronunciation: 'aka' },
      { word: '青', translation: 'blue', index: 1, pronunciation: 'ao' },
      { word: '緑', translation: 'green', index: 2, pronunciation: 'midori' },
      { word: '黄色', translation: 'yellow', index: 3, pronunciation: 'kiiro' },
      { word: '黒', translation: 'black', index: 4, pronunciation: 'kuro' },
      { word: '白', translation: 'white', index: 5, pronunciation: 'shiro' },
      { word: 'オレンジ', translation: 'orange', index: 6, pronunciation: 'orenji' },
      { word: '紫', translation: 'purple', index: 7, pronunciation: 'murasaki' },
      { word: 'ピンク', translation: 'pink', index: 8, pronunciation: 'pinku' },
      { word: '灰色', translation: 'grey', index: 9, pronunciation: 'haiiro' },
    ],
    greetings: [
      { word: 'こんにちは', translation: 'hello', index: 0, pronunciation: 'konnichiwa' },
      { word: 'さようなら', translation: 'goodbye', index: 1, pronunciation: 'sayounara' },
      { word: 'ありがとう', translation: 'thank you', index: 2, pronunciation: 'arigatou' },
      { word: 'お願いします', translation: 'please', index: 3, pronunciation: 'onegaishimasu' },
      { word: 'はい', translation: 'yes', index: 4, pronunciation: 'hai' },
      { word: 'いいえ', translation: 'no', index: 5, pronunciation: 'iie' },
      { word: 'おはよう', translation: 'good morning', index: 6, pronunciation: 'ohayou' },
      { word: 'おやすみ', translation: 'good night', index: 7, pronunciation: 'oyasumi' },
      { word: 'すみません', translation: 'excuse me', index: 8, pronunciation: 'sumimasen' },
      { word: 'お元気ですか', translation: 'how are you?', index: 9, pronunciation: 'ogenki desu ka' },
    ],
    animals: [
      { word: '犬', translation: 'dog', index: 0, pronunciation: 'inu' },
      { word: '猫', translation: 'cat', index: 1, pronunciation: 'neko' },
      { word: '鳥', translation: 'bird', index: 2, pronunciation: 'tori' },
      { word: '魚', translation: 'fish', index: 3, pronunciation: 'sakana' },
      { word: '馬', translation: 'horse', index: 4, pronunciation: 'uma' },
      { word: '牛', translation: 'cow', index: 5, pronunciation: 'ushi' },
      { word: '熊', translation: 'bear', index: 6, pronunciation: 'kuma' },
      { word: '狼', translation: 'wolf', index: 7, pronunciation: 'ookami' },
    ],
    food: [
      { word: 'パン', translation: 'bread', index: 0, pronunciation: 'pan' },
      { word: '水', translation: 'water', index: 1, pronunciation: 'mizu' },
      { word: '牛乳', translation: 'milk', index: 2, pronunciation: 'gyuunyuu' },
      { word: 'りんご', translation: 'apple', index: 3, pronunciation: 'ringo' },
      { word: 'ご飯', translation: 'rice', index: 4, pronunciation: 'gohan' },
      { word: 'チーズ', translation: 'cheese', index: 5, pronunciation: 'chiizu' },
      { word: 'コーヒー', translation: 'coffee', index: 6, pronunciation: 'koohii' },
      { word: '卵', translation: 'egg', index: 7, pronunciation: 'tamago' },
    ],
  },
  ko: {
    numbers: [
      { word: '일', translation: 'one', index: 0, pronunciation: 'il' },
      { word: '이', translation: 'two', index: 1, pronunciation: 'i' },
      { word: '삼', translation: 'three', index: 2, pronunciation: 'sam' },
      { word: '사', translation: 'four', index: 3, pronunciation: 'sa' },
      { word: '오', translation: 'five', index: 4, pronunciation: 'o' },
      { word: '육', translation: 'six', index: 5, pronunciation: 'yuk' },
      { word: '칠', translation: 'seven', index: 6, pronunciation: 'chil' },
      { word: '팔', translation: 'eight', index: 7, pronunciation: 'pal' },
      { word: '구', translation: 'nine', index: 8, pronunciation: 'gu' },
      { word: '십', translation: 'ten', index: 9, pronunciation: 'sip' },
      { word: '십일', translation: 'eleven', index: 10, pronunciation: 'sip-il' },
      { word: '십이', translation: 'twelve', index: 11, pronunciation: 'sip-i' },
      { word: '십삼', translation: 'thirteen', index: 12, pronunciation: 'sip-sam' },
      { word: '십사', translation: 'fourteen', index: 13, pronunciation: 'sip-sa' },
      { word: '십오', translation: 'fifteen', index: 14, pronunciation: 'sip-o' },
      { word: '십육', translation: 'sixteen', index: 15, pronunciation: 'sip-yuk' },
      { word: '십칠', translation: 'seventeen', index: 16, pronunciation: 'sip-chil' },
      { word: '십팔', translation: 'eighteen', index: 17, pronunciation: 'sip-pal' },
      { word: '십구', translation: 'nineteen', index: 18, pronunciation: 'sip-gu' },
      { word: '이십', translation: 'twenty', index: 19, pronunciation: 'isip' },
    ],
    colors: [
      { word: '빨강', translation: 'red', index: 0, pronunciation: 'ppalgang' },
      { word: '파랑', translation: 'blue', index: 1, pronunciation: 'parang' },
      { word: '초록', translation: 'green', index: 2, pronunciation: 'chorok' },
      { word: '노랑', translation: 'yellow', index: 3, pronunciation: 'norang' },
      { word: '검정', translation: 'black', index: 4, pronunciation: 'geomjeong' },
      { word: '하양', translation: 'white', index: 5, pronunciation: 'hayang' },
      { word: '주황', translation: 'orange', index: 6, pronunciation: 'juhwang' },
      { word: '보라', translation: 'purple', index: 7, pronunciation: 'bora' },
      { word: '분홍', translation: 'pink', index: 8, pronunciation: 'bunhong' },
      { word: '회색', translation: 'grey', index: 9, pronunciation: 'hoesaek' },
    ],
    greetings: [
      { word: '안녕하세요', translation: 'hello', index: 0, pronunciation: 'annyeonghaseyo' },
      { word: '안녕히 가세요', translation: 'goodbye', index: 1, pronunciation: 'annyeonghi gaseyo' },
      { word: '감사합니다', translation: 'thank you', index: 2, pronunciation: 'gamsahamnida' },
      { word: '제발', translation: 'please', index: 3, pronunciation: 'jebal' },
      { word: '네', translation: 'yes', index: 4, pronunciation: 'ne' },
      { word: '아니요', translation: 'no', index: 5, pronunciation: 'aniyo' },
      { word: '좋은 아침', translation: 'good morning', index: 6, pronunciation: 'joeun achim' },
      { word: '잘 자', translation: 'good night', index: 7, pronunciation: 'jal ja' },
      { word: '실례합니다', translation: 'excuse me', index: 8, pronunciation: 'sillyehamnida' },
      { word: '어떻게 지내세요', translation: 'how are you?', index: 9, pronunciation: 'eotteoke jinaeseyo' },
    ],
    animals: [
      { word: '개', translation: 'dog', index: 0, pronunciation: 'gae' },
      { word: '고양이', translation: 'cat', index: 1, pronunciation: 'goyangi' },
      { word: '새', translation: 'bird', index: 2, pronunciation: 'sae' },
      { word: '물고기', translation: 'fish', index: 3, pronunciation: 'mulgogi' },
      { word: '말', translation: 'horse', index: 4, pronunciation: 'mal' },
      { word: '소', translation: 'cow', index: 5, pronunciation: 'so' },
      { word: '곰', translation: 'bear', index: 6, pronunciation: 'gom' },
      { word: '늑대', translation: 'wolf', index: 7, pronunciation: 'neukdae' },
    ],
    food: [
      { word: '빵', translation: 'bread', index: 0, pronunciation: 'ppang' },
      { word: '물', translation: 'water', index: 1, pronunciation: 'mul' },
      { word: '우유', translation: 'milk', index: 2, pronunciation: 'uyu' },
      { word: '사과', translation: 'apple', index: 3, pronunciation: 'sagwa' },
      { word: '밥', translation: 'rice', index: 4, pronunciation: 'bap' },
      { word: '치즈', translation: 'cheese', index: 5, pronunciation: 'chijeu' },
      { word: '커피', translation: 'coffee', index: 6, pronunciation: 'keopi' },
      { word: '계란', translation: 'egg', index: 7, pronunciation: 'gyeran' },
    ],
  },
  zh: {
    numbers: [
      { word: '一', translation: 'one', index: 0, pronunciation: 'yī' },
      { word: '二', translation: 'two', index: 1, pronunciation: 'èr' },
      { word: '三', translation: 'three', index: 2, pronunciation: 'sān' },
      { word: '四', translation: 'four', index: 3, pronunciation: 'sì' },
      { word: '五', translation: 'five', index: 4, pronunciation: 'wǔ' },
      { word: '六', translation: 'six', index: 5, pronunciation: 'liù' },
      { word: '七', translation: 'seven', index: 6, pronunciation: 'qī' },
      { word: '八', translation: 'eight', index: 7, pronunciation: 'bā' },
      { word: '九', translation: 'nine', index: 8, pronunciation: 'jiǔ' },
      { word: '十', translation: 'ten', index: 9, pronunciation: 'shí' },
      { word: '十一', translation: 'eleven', index: 10, pronunciation: 'shí yī' },
      { word: '十二', translation: 'twelve', index: 11, pronunciation: 'shí èr' },
      { word: '十三', translation: 'thirteen', index: 12, pronunciation: 'shí sān' },
      { word: '十四', translation: 'fourteen', index: 13, pronunciation: 'shí sì' },
      { word: '十五', translation: 'fifteen', index: 14, pronunciation: 'shí wǔ' },
      { word: '十六', translation: 'sixteen', index: 15, pronunciation: 'shí liù' },
      { word: '十七', translation: 'seventeen', index: 16, pronunciation: 'shí qī' },
      { word: '十八', translation: 'eighteen', index: 17, pronunciation: 'shí bā' },
      { word: '十九', translation: 'nineteen', index: 18, pronunciation: 'shí jiǔ' },
      { word: '二十', translation: 'twenty', index: 19, pronunciation: 'èrshí' },
    ],
    colors: [
      { word: '红色', translation: 'red', index: 0, pronunciation: 'hóng sè' },
      { word: '蓝色', translation: 'blue', index: 1, pronunciation: 'lán sè' },
      { word: '绿色', translation: 'green', index: 2, pronunciation: 'lǜ sè' },
      { word: '黄色', translation: 'yellow', index: 3, pronunciation: 'huáng sè' },
      { word: '黑色', translation: 'black', index: 4, pronunciation: 'hēi sè' },
      { word: '白色', translation: 'white', index: 5, pronunciation: 'bái sè' },
      { word: '橙色', translation: 'orange', index: 6, pronunciation: 'chéng sè' },
      { word: '紫色', translation: 'purple', index: 7, pronunciation: 'zǐ sè' },
      { word: '粉色', translation: 'pink', index: 8, pronunciation: 'fěn sè' },
      { word: '灰色', translation: 'grey', index: 9, pronunciation: 'huī sè' },
    ],
    greetings: [
      { word: '你好', translation: 'hello', index: 0, pronunciation: 'nǐ hǎo' },
      { word: '再见', translation: 'goodbye', index: 1, pronunciation: 'zài jiàn' },
      { word: '谢谢', translation: 'thank you', index: 2, pronunciation: 'xiè xiè' },
      { word: '请', translation: 'please', index: 3, pronunciation: 'qǐng' },
      { word: '是', translation: 'yes', index: 4, pronunciation: 'shì' },
      { word: '不是', translation: 'no', index: 5, pronunciation: 'bú shì' },
      { word: '早上好', translation: 'good morning', index: 6, pronunciation: 'zǎo shàng hǎo' },
      { word: '晚安', translation: 'good night', index: 7, pronunciation: 'wǎn ān' },
      { word: '对不起', translation: 'excuse me', index: 8, pronunciation: 'duì bù qǐ' },
      { word: '你好吗', translation: 'how are you?', index: 9, pronunciation: 'nǐ hǎo ma' },
    ],
    animals: [
      { word: '狗', translation: 'dog', index: 0, pronunciation: 'gǒu' },
      { word: '猫', translation: 'cat', index: 1, pronunciation: 'māo' },
      { word: '鸟', translation: 'bird', index: 2, pronunciation: 'niǎo' },
      { word: '鱼', translation: 'fish', index: 3, pronunciation: 'yú' },
      { word: '马', translation: 'horse', index: 4, pronunciation: 'mǎ' },
      { word: '牛', translation: 'cow', index: 5, pronunciation: 'niú' },
      { word: '熊', translation: 'bear', index: 6, pronunciation: 'xióng' },
      { word: '狼', translation: 'wolf', index: 7, pronunciation: 'láng' },
    ],
    food: [
      { word: '面包', translation: 'bread', index: 0, pronunciation: 'miàn bāo' },
      { word: '水', translation: 'water', index: 1, pronunciation: 'shuǐ' },
      { word: '牛奶', translation: 'milk', index: 2, pronunciation: 'niú nǎi' },
      { word: '苹果', translation: 'apple', index: 3, pronunciation: 'píng guǒ' },
      { word: '米饭', translation: 'rice', index: 4, pronunciation: 'mǐ fàn' },
      { word: '奶酪', translation: 'cheese', index: 5, pronunciation: 'nǎi lào' },
      { word: '咖啡', translation: 'coffee', index: 6, pronunciation: 'kā fēi' },
      { word: '鸡蛋', translation: 'egg', index: 7, pronunciation: 'jī dàn' },
    ],
  },
  ru: {
    numbers: [
      { word: 'один', translation: 'one', index: 0 },
      { word: 'два', translation: 'two', index: 1 },
      { word: 'три', translation: 'three', index: 2 },
      { word: 'четыре', translation: 'four', index: 3 },
      { word: 'пять', translation: 'five', index: 4 },
      { word: 'шесть', translation: 'six', index: 5 },
      { word: 'семь', translation: 'seven', index: 6 },
      { word: 'восемь', translation: 'eight', index: 7 },
      { word: 'девять', translation: 'nine', index: 8 },
      { word: 'десять', translation: 'ten', index: 9 },
      { word: 'одиннадцать', translation: 'eleven', index: 10 },
      { word: 'двенадцать', translation: 'twelve', index: 11 },
      { word: 'тринадцать', translation: 'thirteen', index: 12 },
      { word: 'четырнадцать', translation: 'fourteen', index: 13 },
      { word: 'пятнадцать', translation: 'fifteen', index: 14 },
      { word: 'шестнадцать', translation: 'sixteen', index: 15 },
      { word: 'семнадцать', translation: 'seventeen', index: 16 },
      { word: 'восемнадцать', translation: 'eighteen', index: 17 },
      { word: 'девятнадцать', translation: 'nineteen', index: 18 },
      { word: 'двадцать', translation: 'twenty', index: 19 },
    ],
    colors: [
      { word: 'красный', translation: 'red', index: 0, pronunciation: 'KRAS-niy' },
      { word: 'синий', translation: 'blue', index: 1, pronunciation: 'SEE-niy' },
      { word: 'зелёный', translation: 'green', index: 2, pronunciation: 'zee-LYO-niy' },
      { word: 'жёлтый', translation: 'yellow', index: 3, pronunciation: 'ZHOL-tiy' },
      { word: 'чёрный', translation: 'black', index: 4, pronunciation: 'CHOR-niy' },
      { word: 'белый', translation: 'white', index: 5, pronunciation: 'BYEH-liy' },
      { word: 'оранжевый', translation: 'orange', index: 6, pronunciation: 'ah-RAN-zheh-viy' },
      { word: 'фиолетовый', translation: 'purple', index: 7, pronunciation: 'fee-ah-LYEH-tah-viy' },
      { word: 'розовый', translation: 'pink', index: 8, pronunciation: 'ROH-zah-viy' },
      { word: 'серый', translation: 'grey', index: 9, pronunciation: 'SYEH-riy' },
    ],
    greetings: [
      { word: 'привет', translation: 'hello', index: 0, pronunciation: 'pree-VYET' },
      { word: 'до свидания', translation: 'goodbye', index: 1, pronunciation: 'da svee-DAH-nya' },
      { word: 'спасибо', translation: 'thank you', index: 2, pronunciation: 'spah-SEE-bah' },
      { word: 'пожалуйста', translation: 'please', index: 3, pronunciation: 'pah-ZHAH-lus-tah' },
      { word: 'да', translation: 'yes', index: 4, pronunciation: 'dah' },
      { word: 'нет', translation: 'no', index: 5, pronunciation: 'nyet' },
      { word: 'доброе утро', translation: 'good morning', index: 6, pronunciation: 'DOH-brah-yeh OO-trah' },
      { word: 'спокойной ночи', translation: 'good night', index: 7, pronunciation: 'spah-KOY-nay NOH-chee' },
      { word: 'извините', translation: 'excuse me', index: 8, pronunciation: 'eez-vee-NEE-tyeh' },
      { word: 'как дела', translation: 'how are you?', index: 9, pronunciation: 'kahk dyeh-LAH' },
    ],
    animals: [
      { word: 'собака', translation: 'dog', index: 0, pronunciation: 'sah-BAH-kah' },
      { word: 'кошка', translation: 'cat', index: 1, pronunciation: 'KOSH-kah' },
      { word: 'птица', translation: 'bird', index: 2, pronunciation: 'PTEE-tsah' },
      { word: 'рыба', translation: 'fish', index: 3, pronunciation: 'RI-bah' },
      { word: 'лошадь', translation: 'horse', index: 4, pronunciation: 'LOH-shat' },
      { word: 'корова', translation: 'cow', index: 5, pronunciation: 'kah-ROH-vah' },
      { word: 'медведь', translation: 'bear', index: 6, pronunciation: 'meed-VYET' },
      { word: 'волк', translation: 'wolf', index: 7, pronunciation: 'volk' },
    ],
    food: [
      { word: 'хлеб', translation: 'bread', index: 0, pronunciation: 'khlyep' },
      { word: 'вода', translation: 'water', index: 1, pronunciation: 'vah-DAH' },
      { word: 'молоко', translation: 'milk', index: 2, pronunciation: 'mah-lah-KOH' },
      { word: 'яблоко', translation: 'apple', index: 3, pronunciation: 'YAH-blah-kah' },
      { word: 'рис', translation: 'rice', index: 4, pronunciation: 'rees' },
      { word: 'сыр', translation: 'cheese', index: 5, pronunciation: 'sir' },
      { word: 'кофе', translation: 'coffee', index: 6, pronunciation: 'KOH-fyeh' },
      { word: 'яйцо', translation: 'egg', index: 7, pronunciation: 'yai-TSOH' },
    ],
  },
  ar: {
    numbers: [
      { word: 'واحد', translation: 'one', index: 0 },
      { word: 'اثنان', translation: 'two', index: 1 },
      { word: 'ثلاثة', translation: 'three', index: 2 },
      { word: 'أربعة', translation: 'four', index: 3 },
      { word: 'خمسة', translation: 'five', index: 4 },
      { word: 'ستة', translation: 'six', index: 5 },
      { word: 'سبعة', translation: 'seven', index: 6 },
      { word: 'ثمانية', translation: 'eight', index: 7 },
      { word: 'تسعة', translation: 'nine', index: 8 },
      { word: 'عشرة', translation: 'ten', index: 9 },
      { word: 'أحد عشر', translation: 'eleven', index: 10 },
      { word: 'اثنا عشر', translation: 'twelve', index: 11 },
      { word: 'ثلاثة عشر', translation: 'thirteen', index: 12 },
      { word: 'أربعة عشر', translation: 'fourteen', index: 13 },
      { word: 'خمسة عشر', translation: 'fifteen', index: 14 },
      { word: 'ستة عشر', translation: 'sixteen', index: 15 },
      { word: 'سبعة عشر', translation: 'seventeen', index: 16 },
      { word: 'ثمانية عشر', translation: 'eighteen', index: 17 },
      { word: 'تسعة عشر', translation: 'nineteen', index: 18 },
      { word: 'عشرون', translation: 'twenty', index: 19 },
    ],
    colors: [
      { word: 'أحمر', translation: 'red', index: 0, pronunciation: 'ahmar' },
      { word: 'أزرق', translation: 'blue', index: 1, pronunciation: 'azraq' },
      { word: 'أخضر', translation: 'green', index: 2, pronunciation: 'akhdar' },
      { word: 'أصفر', translation: 'yellow', index: 3, pronunciation: 'asfar' },
      { word: 'أسود', translation: 'black', index: 4, pronunciation: 'aswad' },
      { word: 'أبيض', translation: 'white', index: 5, pronunciation: 'abyad' },
      { word: 'برتقالي', translation: 'orange', index: 6, pronunciation: 'burtuqali' },
      { word: 'بنفسجي', translation: 'purple', index: 7, pronunciation: 'banafsaji' },
      { word: 'وردي', translation: 'pink', index: 8, pronunciation: 'wardi' },
      { word: 'رمادي', translation: 'grey', index: 9, pronunciation: 'ramadi' },
    ],
    greetings: [
      { word: 'مرحبا', translation: 'hello', index: 0, pronunciation: 'marhaban' },
      { word: 'مع السلامة', translation: 'goodbye', index: 1, pronunciation: 'maa as-salama' },
      { word: 'شكرا', translation: 'thank you', index: 2, pronunciation: 'shukran' },
      { word: 'من فضلك', translation: 'please', index: 3, pronunciation: 'min fadlik' },
      { word: 'نعم', translation: 'yes', index: 4, pronunciation: 'naam' },
      { word: 'لا', translation: 'no', index: 5, pronunciation: 'la' },
      { word: 'صباح الخير', translation: 'good morning', index: 6, pronunciation: 'sabah al-khayr' },
      { word: 'تصبح على خير', translation: 'good night', index: 7, pronunciation: 'tusbih ala khayr' },
      { word: 'عفوا', translation: 'excuse me', index: 8, pronunciation: 'afwan' },
      { word: 'كيف حالك', translation: 'how are you?', index: 9, pronunciation: 'kayfa haluk' },
    ],
    animals: [
      { word: 'كلب', translation: 'dog', index: 0, pronunciation: 'kalb' },
      { word: 'قطة', translation: 'cat', index: 1, pronunciation: 'qitta' },
      { word: 'طائر', translation: 'bird', index: 2, pronunciation: 'tair' },
      { word: 'سمكة', translation: 'fish', index: 3, pronunciation: 'samaka' },
      { word: 'حصان', translation: 'horse', index: 4, pronunciation: 'hisan' },
      { word: 'بقرة', translation: 'cow', index: 5, pronunciation: 'baqara' },
      { word: 'دب', translation: 'bear', index: 6, pronunciation: 'dubb' },
      { word: 'ذئب', translation: 'wolf', index: 7, pronunciation: 'dhib' },
    ],
    food: [
      { word: 'خبز', translation: 'bread', index: 0, pronunciation: 'khubz' },
      { word: 'ماء', translation: 'water', index: 1, pronunciation: 'maa' },
      { word: 'حليب', translation: 'milk', index: 2, pronunciation: 'halib' },
      { word: 'تفاحة', translation: 'apple', index: 3, pronunciation: 'tuffaha' },
      { word: 'أرز', translation: 'rice', index: 4, pronunciation: 'aruzz' },
      { word: 'جبن', translation: 'cheese', index: 5, pronunciation: 'jubn' },
      { word: 'قهوة', translation: 'coffee', index: 6, pronunciation: 'qahwa' },
      { word: 'بيضة', translation: 'egg', index: 7, pronunciation: 'bayda' },
    ],
  },
  hi: {
    numbers: [
      { word: 'एक', translation: 'one', index: 0 },
      { word: 'दो', translation: 'two', index: 1 },
      { word: 'तीन', translation: 'three', index: 2 },
      { word: 'चार', translation: 'four', index: 3 },
      { word: 'पाँच', translation: 'five', index: 4 },
      { word: 'छह', translation: 'six', index: 5 },
      { word: 'सात', translation: 'seven', index: 6 },
      { word: 'आठ', translation: 'eight', index: 7 },
      { word: 'नौ', translation: 'nine', index: 8 },
      { word: 'दस', translation: 'ten', index: 9 },
      { word: 'ग्यारह', translation: 'eleven', index: 10 },
      { word: 'बारह', translation: 'twelve', index: 11 },
      { word: 'तेरह', translation: 'thirteen', index: 12 },
      { word: 'चौदह', translation: 'fourteen', index: 13 },
      { word: 'पंद्रह', translation: 'fifteen', index: 14 },
      { word: 'सोलह', translation: 'sixteen', index: 15 },
      { word: 'सत्रह', translation: 'seventeen', index: 16 },
      { word: 'अठारह', translation: 'eighteen', index: 17 },
      { word: 'उन्नीस', translation: 'nineteen', index: 18 },
      { word: 'बीस', translation: 'twenty', index: 19 },
    ],
    colors: [
      { word: 'लाल', translation: 'red', index: 0, pronunciation: 'laal' },
      { word: 'नीला', translation: 'blue', index: 1, pronunciation: 'neela' },
      { word: 'हरा', translation: 'green', index: 2, pronunciation: 'hara' },
      { word: 'पीला', translation: 'yellow', index: 3, pronunciation: 'peela' },
      { word: 'काला', translation: 'black', index: 4, pronunciation: 'kaala' },
      { word: 'सफ़ेद', translation: 'white', index: 5, pronunciation: 'safed' },
      { word: 'नारंगी', translation: 'orange', index: 6, pronunciation: 'naarangi' },
      { word: 'बैंगनी', translation: 'purple', index: 7, pronunciation: 'baingani' },
      { word: 'गुलाबी', translation: 'pink', index: 8, pronunciation: 'gulaabi' },
      { word: 'धूसर', translation: 'grey', index: 9, pronunciation: 'dhoosar' },
    ],
    greetings: [
      { word: 'नमस्ते', translation: 'hello', index: 0, pronunciation: 'namaste' },
      { word: 'अलविदा', translation: 'goodbye', index: 1, pronunciation: 'alvida' },
      { word: 'धन्यवाद', translation: 'thank you', index: 2, pronunciation: 'dhanyavaad' },
      { word: 'कृपया', translation: 'please', index: 3, pronunciation: 'kripaya' },
      { word: 'हाँ', translation: 'yes', index: 4, pronunciation: 'haan' },
      { word: 'नहीं', translation: 'no', index: 5, pronunciation: 'nahin' },
      { word: 'सुप्रभात', translation: 'good morning', index: 6, pronunciation: 'suprabhaat' },
      { word: 'शुभ रात्रि', translation: 'good night', index: 7, pronunciation: 'shubh raatri' },
      { word: 'क्षमा करें', translation: 'excuse me', index: 8, pronunciation: 'kshama karen' },
      { word: 'आप कैसे हैं', translation: 'how are you?', index: 9, pronunciation: 'aap kaise hain' },
    ],
    animals: [
      { word: 'कुत्ता', translation: 'dog', index: 0, pronunciation: 'kutta' },
      { word: 'बिल्ली', translation: 'cat', index: 1, pronunciation: 'billi' },
      { word: 'पक्षी', translation: 'bird', index: 2, pronunciation: 'pakshi' },
      { word: 'मछली', translation: 'fish', index: 3, pronunciation: 'machhli' },
      { word: 'घोड़ा', translation: 'horse', index: 4, pronunciation: 'ghoda' },
      { word: 'गाय', translation: 'cow', index: 5, pronunciation: 'gaay' },
      { word: 'भालू', translation: 'bear', index: 6, pronunciation: 'bhaalu' },
      { word: 'भेड़िया', translation: 'wolf', index: 7, pronunciation: 'bhediya' },
    ],
    food: [
      { word: 'रोटी', translation: 'bread', index: 0, pronunciation: 'roti' },
      { word: 'पानी', translation: 'water', index: 1, pronunciation: 'paani' },
      { word: 'दूध', translation: 'milk', index: 2, pronunciation: 'doodh' },
      { word: 'सेब', translation: 'apple', index: 3, pronunciation: 'seb' },
      { word: 'चावल', translation: 'rice', index: 4, pronunciation: 'chaawal' },
      { word: 'पनीर', translation: 'cheese', index: 5, pronunciation: 'paneer' },
      { word: 'कॉफ़ी', translation: 'coffee', index: 6, pronunciation: 'coffee' },
      { word: 'अंडा', translation: 'egg', index: 7, pronunciation: 'anda' },
    ],
  },
  th: {
    numbers: [
      { word: 'หนึ่ง', translation: 'one', index: 0, pronunciation: 'nueng' },
      { word: 'สอง', translation: 'two', index: 1, pronunciation: 'song' },
      { word: 'สาม', translation: 'three', index: 2, pronunciation: 'sam' },
      { word: 'สี่', translation: 'four', index: 3, pronunciation: 'si' },
      { word: 'ห้า', translation: 'five', index: 4, pronunciation: 'ha' },
      { word: 'หก', translation: 'six', index: 5, pronunciation: 'hok' },
      { word: 'เจ็ด', translation: 'seven', index: 6, pronunciation: 'chet' },
      { word: 'แปด', translation: 'eight', index: 7, pronunciation: 'paet' },
      { word: 'เก้า', translation: 'nine', index: 8, pronunciation: 'kao' },
      { word: 'สิบ', translation: 'ten', index: 9, pronunciation: 'sip' },
      { word: 'สิบเอ็ด', translation: 'eleven', index: 10, pronunciation: 'sip-et' },
      { word: 'สิบสอง', translation: 'twelve', index: 11, pronunciation: 'sip-song' },
      { word: 'สิบสาม', translation: 'thirteen', index: 12, pronunciation: 'sip-sam' },
      { word: 'สิบสี่', translation: 'fourteen', index: 13, pronunciation: 'sip-si' },
      { word: 'สิบห้า', translation: 'fifteen', index: 14, pronunciation: 'sip-ha' },
      { word: 'สิบหก', translation: 'sixteen', index: 15, pronunciation: 'sip-hok' },
      { word: 'สิบเจ็ด', translation: 'seventeen', index: 16, pronunciation: 'sip-chet' },
      { word: 'สิบแปด', translation: 'eighteen', index: 17, pronunciation: 'sip-paet' },
      { word: 'สิบเก้า', translation: 'nineteen', index: 18, pronunciation: 'sip-kao' },
      { word: 'ยี่สิบ', translation: 'twenty', index: 19, pronunciation: 'yi-sip' },
    ],
    colors: [
      { word: 'สีแดง', translation: 'red', index: 0, pronunciation: 'si daeng' },
      { word: 'สีน้ำเงิน', translation: 'blue', index: 1, pronunciation: 'si nam ngoen' },
      { word: 'สีเขียว', translation: 'green', index: 2, pronunciation: 'si khiao' },
      { word: 'สีเหลือง', translation: 'yellow', index: 3, pronunciation: 'si lueang' },
      { word: 'สีดำ', translation: 'black', index: 4, pronunciation: 'si dam' },
      { word: 'สีขาว', translation: 'white', index: 5, pronunciation: 'si khao' },
      { word: 'สีส้ม', translation: 'orange', index: 6, pronunciation: 'si som' },
      { word: 'สีม่วง', translation: 'purple', index: 7, pronunciation: 'si muang' },
      { word: 'สีชมพู', translation: 'pink', index: 8, pronunciation: 'si chomphu' },
      { word: 'สีเทา', translation: 'grey', index: 9, pronunciation: 'si thao' },
    ],
    greetings: [
      { word: 'สวัสดี', translation: 'hello', index: 0, pronunciation: 'sawatdi' },
      { word: 'ลาก่อน', translation: 'goodbye', index: 1, pronunciation: 'la kon' },
      { word: 'ขอบคุณ', translation: 'thank you', index: 2, pronunciation: 'khop khun' },
      { word: 'กรุณา', translation: 'please', index: 3, pronunciation: 'karuna' },
      { word: 'ใช่', translation: 'yes', index: 4, pronunciation: 'chai' },
      { word: 'ไม่', translation: 'no', index: 5, pronunciation: 'mai' },
      { word: 'อรุณสวัสดิ์', translation: 'good morning', index: 6, pronunciation: 'arun sawat' },
      { word: 'ราตรีสวัสดิ์', translation: 'good night', index: 7, pronunciation: 'ratri sawat' },
      { word: 'ขอโทษ', translation: 'excuse me', index: 8, pronunciation: 'kho thot' },
      { word: 'สบายดีไหม', translation: 'how are you?', index: 9, pronunciation: 'sabai di mai' },
    ],
    animals: [
      { word: 'หมา', translation: 'dog', index: 0, pronunciation: 'ma' },
      { word: 'แมว', translation: 'cat', index: 1, pronunciation: 'maeo' },
      { word: 'นก', translation: 'bird', index: 2, pronunciation: 'nok' },
      { word: 'ปลา', translation: 'fish', index: 3, pronunciation: 'pla' },
      { word: 'ม้า', translation: 'horse', index: 4, pronunciation: 'ma' },
      { word: 'วัว', translation: 'cow', index: 5, pronunciation: 'wua' },
      { word: 'หมี', translation: 'bear', index: 6, pronunciation: 'mi' },
      { word: 'หมาป่า', translation: 'wolf', index: 7, pronunciation: 'ma pa' },
    ],
    food: [
      { word: 'ขนมปัง', translation: 'bread', index: 0, pronunciation: 'khanom pang' },
      { word: 'น้ำ', translation: 'water', index: 1, pronunciation: 'nam' },
      { word: 'นม', translation: 'milk', index: 2, pronunciation: 'nom' },
      { word: 'แอปเปิ้ล', translation: 'apple', index: 3, pronunciation: 'aeppoen' },
      { word: 'ข้าว', translation: 'rice', index: 4, pronunciation: 'khao' },
      { word: 'ชีส', translation: 'cheese', index: 5, pronunciation: 'chis' },
      { word: 'กาแฟ', translation: 'coffee', index: 6, pronunciation: 'kafae' },
      { word: 'ไข่', translation: 'egg', index: 7, pronunciation: 'khai' },
    ],
  },
};

export interface LocalScore {
  id: number;
  userId: number;
  language: string;
  category: string;
  count: number;
  createdAt: string;
}

const LOCAL_SCORES_KEY = 'lok-lingu-local-scores';

export function saveLocalScore(score: Omit<LocalScore, 'id' | 'createdAt'>) {
  try {
    const existingStr = localStorage.getItem(LOCAL_SCORES_KEY);
    const scores: LocalScore[] = existingStr ? JSON.parse(existingStr) : [];
    const newScore: LocalScore = {
      ...score,
      id: Date.now(),
      createdAt: new Date().toISOString(),
    };
    scores.unshift(newScore);
    localStorage.setItem(LOCAL_SCORES_KEY, JSON.stringify(scores.slice(0, 100)));
  } catch (err) {
    console.error('Failed to save score locally', err);
  }
}

export function getLocalScores(userId?: number): LocalScore[] {
  try {
    const existingStr = localStorage.getItem(LOCAL_SCORES_KEY);
    if (!existingStr) return [];
    const scores: LocalScore[] = JSON.parse(existingStr);
    return userId ? scores.filter((s) => s.userId === userId) : scores;
  } catch (err) {
    console.error('Failed to read local scores', err);
    return [];
  }
}

export function getLocalUserStats(userId: number) {
  const scores = getLocalScores(userId);
  const totalGames = scores.length;
  const bestCount = scores.length > 0 ? Math.max(...scores.map((s) => s.count)) : 0;
  const totalWordsSpoken = scores.reduce((acc, s) => acc + s.count, 0);

  const langCounts: Record<string, number> = {};
  const catCounts: Record<string, number> = {};
  for (const s of scores) {
    langCounts[s.language] = (langCounts[s.language] ?? 0) + 1;
    catCounts[s.category] = (catCounts[s.category] ?? 0) + 1;
  }

  const favoriteLanguage =
    Object.keys(langCounts).sort((a, b) => langCounts[b] - langCounts[a])[0] ?? null;
  const favoriteCategory =
    Object.keys(catCounts).sort((a, b) => catCounts[b] - catCounts[a])[0] ?? null;

  return {
    userId,
    totalGames,
    bestCount,
    totalWordsSpoken,
    favoriteLanguage,
    favoriteCategory,
    personalBests: scores.slice(0, 10),
  };
}

const LIFETIME_PREFIX = 'lok-lingu-lifetime-';

/**
 * Lifetime words for one language, the series behind the stats pie.
 * Only the drawing game used to write these, so a voice player's chart
 * stayed empty no matter how long they played.
 */
export function incrementLifetimeWords(language: string, by = 1): void {
  if (!language || language === 'tokens') return;
  try {
    const key = `${LIFETIME_PREFIX}${language}`;
    const current = parseInt(localStorage.getItem(key) || '0', 10) || 0;
    localStorage.setItem(key, String(current + by));
  } catch {
    /* storage unavailable (private mode) — scores still save per run */
  }
}

export function getLifetimeWords(): Record<string, number> {
  const out: Record<string, number> = {};
  try {
    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i);
      if (!key?.startsWith(LIFETIME_PREFIX)) continue;
      const lang = key.slice(LIFETIME_PREFIX.length);
      if (lang === 'tokens') continue;
      const val = parseInt(localStorage.getItem(key) || '0', 10) || 0;
      if (val > 0) out[lang] = val;
    }
  } catch {
    /* ignore */
  }
  return out;
}
